{
    "kind": "discovery#restDescription",
    "etag": "\"tbys6C40o18GZwyMen5GMkdK-3s/GcEQbY_uWqf8lGSMWrpoGmCk7zY\"",
    "discoveryVersion": "v1",
    "id": "drive:v2",
    "name": "drive",
    "version": "v2",
    "title": "Drive API",
    "description": "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.",
    "documentationLink": "https://developers.google.com/drive/",
    "protocol": "rest",
    "rootUrl": "https://www.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
        ]
    },
    "resources": [
        {
            "name": "permissions",
            "methods": [
                {
                    "name": "update",
                    "desc": "Updates a permission.",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "permissionId",
                            "desc": "The ID for the permission.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "transferOwnership",
                            "desc": "Whether changing a role to 'owner' downgrades the current owners to writers. Does nothing if the specified role is not 'owner'.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "removeExpiration",
                            "desc": "Whether to remove the expiration date.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a permission from a file or Team Drive.",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "permissionId",
                            "desc": "The ID for the permission.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a permission by ID.",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "permissionId",
                            "desc": "The ID for the permission.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "getIdForEmail",
                    "desc": "Returns the permission ID for an email address.",
                    "path": "permissionIds/{email}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "email",
                            "desc": "The email address for which to return a permission ID",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Inserts a permission for a file or Team Drive.",
                    "path": "files/{fileId}/permissions",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "emailMessage",
                            "desc": "A custom message to include in notification emails.",
                            "type": "string"
                        },
                        {
                            "name": "sendNotificationEmails",
                            "desc": "Whether to send notification emails when sharing to users or groups. This parameter is ignored and an email is sent if the role is owner.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a file's or Team Drive's permissions.",
                    "path": "files/{fileId}/permissions",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "The maximum number of permissions to return per page. When not set for files in a Team Drive, at most 100 results will be returned. When not set for files that are not in a Team Drive, the entire list will be returned.",
                            "type": "int32",
                            "min": "1",
                            "max": "100"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates a permission using patch semantics.",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file or Team Drive.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "permissionId",
                            "desc": "The ID for the permission.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "transferOwnership",
                            "desc": "Whether changing a role to 'owner' downgrades the current owners to writers. Does nothing if the specified role is not 'owner'.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "removeExpiration",
                            "desc": "Whether to remove the expiration date.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                }
            ]
        },
        {
            "name": "realtime",
            "methods": [
                {
                    "name": "get",
                    "desc": "Exports the contents of the Realtime API data model associated with this file as JSON.",
                    "path": "files/{fileId}/realtime",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file that the Realtime API data model is associated with.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "revision",
                            "desc": "The revision of the Realtime API data model to export. Revisions start at 1 (the initial empty data model) and are incremented with each change. If this parameter is excluded, the most recent data model will be returned.",
                            "type": "int32",
                            "min": "1"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Overwrites the Realtime API data model associated with this file with the provided JSON data model.",
                    "path": "files/{fileId}/realtime",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file that the Realtime API data model is associated with.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "baseRevision",
                            "desc": "The revision of the model to diff the uploaded model against. If set, the uploaded model is diffed against the provided revision and those differences are merged with any changes made to the model after the provided revision. If not set, the uploaded model replaces the current model on the server.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "replies",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a reply.",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "replyId",
                            "desc": "The ID of the reply.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a reply.",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "replyId",
                            "desc": "The ID of the reply.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeDeleted",
                            "desc": "If set, this will succeed when retrieving a deleted reply.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a new reply to the given comment.",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists all of the replies to a comment.",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeDeleted",
                            "desc": "If set, all replies, including deleted replies (with content stripped) will be returned.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maximum number of replies to include in the response, used for paging.",
                            "type": "int32",
                            "default": "20",
                            "min": "0",
                            "max": "100"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The continuation token, used to page through large result sets. To get the next page of results, set this parameter to the value of \"nextPageToken\" from the previous response.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates an existing reply. This method supports patch semantics.",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "replyId",
                            "desc": "The ID of the reply.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates an existing reply.",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "replyId",
                            "desc": "The ID of the reply.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "revisions",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Removes a revision.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "revisionId",
                            "desc": "The ID of the revision.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a specific revision.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "revisionId",
                            "desc": "The ID of the revision.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a file's revisions.",
                    "path": "files/{fileId}/revisions",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of revisions to return.",
                            "type": "int32",
                            "default": "200",
                            "min": "1",
                            "max": "1000"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Page token for revisions. To get the next page of results, set this parameter to the value of \"nextPageToken\" from the previous response.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates a revision. This method supports patch semantics.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "revisionId",
                            "desc": "The ID for the revision.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a revision.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "revisionId",
                            "desc": "The ID for the revision.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "changes",
            "methods": [
                {
                    "name": "get",
                    "desc": "Gets a specific change.",
                    "path": "changes/{changeId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "changeId",
                            "desc": "The ID of the change.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "teamDriveId",
                            "desc": "The Team Drive from which the change will be returned.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "getStartPageToken",
                    "desc": "Gets the starting pageToken for listing future changes.",
                    "path": "changes/startPageToken",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "teamDriveId",
                            "desc": "The ID of the Team Drive for which the starting pageToken for listing future changes from that Team Drive will be returned.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists the changes for a user or Team Drive.",
                    "path": "changes",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "startChangeId",
                            "desc": "Change ID to start listing changes from.",
                            "type": "int64"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "teamDriveId",
                            "desc": "The Team Drive from which changes will be returned. If specified the change IDs will be reflective of the Team Drive; use the combined Team Drive ID and change ID as an identifier.",
                            "type": "string"
                        },
                        {
                            "name": "includeCorpusRemovals",
                            "desc": "Whether changes should include the file resource if the file is still accessible by the user at the time of the request, even when a file was removed from the list of changes and there will be no further change entries for this file.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "includeSubscribed",
                            "desc": "Whether to include public files the user has opened and shared files. When set to false, the list only includes owned files plus any shared or public files the user has explicitly added to a folder they own.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of changes to return.",
                            "type": "int32",
                            "default": "100",
                            "min": "1"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response or to the response from the getStartPageToken method.",
                            "type": "string"
                        },
                        {
                            "name": "includeDeleted",
                            "desc": "Whether to include changes indicating that items have been removed from the list of changes, for example by deletion or loss of access.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "includeTeamDriveItems",
                            "desc": "Whether Team Drive files or changes should be included in results.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "spaces",
                            "desc": "A comma-separated list of spaces to query. Supported values are 'drive', 'appDataFolder' and 'photos'.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "watch",
                    "desc": "Subscribe to changes for a user.",
                    "path": "changes/watch",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeDeleted",
                            "desc": "Whether to include changes indicating that items have been removed from the list of changes, for example by deletion or loss of access.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "includeTeamDriveItems",
                            "desc": "Whether Team Drive files or changes should be included in results.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response or to the response from the getStartPageToken method.",
                            "type": "string"
                        },
                        {
                            "name": "includeCorpusRemovals",
                            "desc": "Whether changes should include the file resource if the file is still accessible by the user at the time of the request, even when a file was removed from the list of changes and there will be no further change entries for this file.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "includeSubscribed",
                            "desc": "Whether to include public files the user has opened and shared files. When set to false, the list only includes owned files plus any shared or public files the user has explicitly added to a folder they own.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of changes to return.",
                            "type": "int32",
                            "default": "100",
                            "min": "1"
                        },
                        {
                            "name": "spaces",
                            "desc": "A comma-separated list of spaces to query. Supported values are 'drive', 'appDataFolder' and 'photos'.",
                            "type": "string"
                        },
                        {
                            "name": "startChangeId",
                            "desc": "Change ID to start listing changes from.",
                            "type": "int64"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "teamDriveId",
                            "desc": "The Team Drive from which changes will be returned. If specified the change IDs will be reflective of the Team Drive; use the combined Team Drive ID and change ID as an identifier.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "files",
            "methods": [
                {
                    "name": "watch",
                    "desc": "Subscribe to changes on a file",
                    "path": "files/{fileId}/watch",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file in question.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "revisionId",
                            "desc": "Specifies the Revision ID that should be downloaded. Ignored unless alt=media is specified.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "updateViewedDate",
                            "desc": "Deprecated: Use files.update with modifiedDateBehavior=noChange, updateViewedDate=true and an empty request body.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "acknowledgeAbuse",
                            "desc": "Whether the user is acknowledging the risk of downloading known malware or other abusive files.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "projection",
                            "desc": "This parameter is deprecated and has no function.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "BASIC",
                                    "desc": "Deprecated"
                                },
                                {
                                    "name": "FULL",
                                    "desc": "Deprecated"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "copy",
                    "desc": "Creates a copy of the specified file.",
                    "path": "files/{fileId}/copy",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.photos.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to copy.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "visibility",
                            "desc": "The visibility of the new file. This parameter is only relevant when the source is not a native Google Doc and convert=false.",
                            "type": "string",
                            "default": "DEFAULT",
                            "enum": [
                                {
                                    "name": "DEFAULT",
                                    "desc": "The visibility of the new file is determined by the user's default visibility/sharing policies."
                                },
                                {
                                    "name": "PRIVATE",
                                    "desc": "The new file will be visible to only the owner."
                                }
                            ]
                        },
                        {
                            "name": "convert",
                            "desc": "Whether to convert this file to the corresponding Google Docs format.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "ocr",
                            "desc": "Whether to attempt OCR on .jpg, .png, .gif, or .pdf uploads.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "pinned",
                            "desc": "Whether to pin the head revision of the new copy. A file can have a maximum of 200 pinned revisions.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "ocrLanguage",
                            "desc": "If ocr is true, hints at the language to use. Valid values are BCP 47 codes.",
                            "type": "string"
                        },
                        {
                            "name": "timedTextLanguage",
                            "desc": "The language of the timed text.",
                            "type": "string"
                        },
                        {
                            "name": "timedTextTrackName",
                            "desc": "The timed text track name.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file or be an organizer on the parent for Team Drive files.",
                    "path": "files/{fileId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to delete.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "emptyTrash",
                    "desc": "Permanently deletes all of the user's trashed files.",
                    "path": "files/trash",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                {
                    "name": "generateIds",
                    "desc": "Generates a set of file IDs which can be provided in insert requests.",
                    "path": "files/generateIds",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of IDs to return.",
                            "type": "int32",
                            "default": "10",
                            "min": "1",
                            "max": "1000"
                        },
                        {
                            "name": "space",
                            "desc": "The space in which the IDs can be used to create new files. Supported values are 'drive' and 'appDataFolder'.",
                            "type": "string",
                            "default": "drive"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a file's metadata by ID.",
                    "path": "files/{fileId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID for the file in question.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "updateViewedDate",
                            "desc": "Deprecated: Use files.update with modifiedDateBehavior=noChange, updateViewedDate=true and an empty request body.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "acknowledgeAbuse",
                            "desc": "Whether the user is acknowledging the risk of downloading known malware or other abusive files.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "projection",
                            "desc": "This parameter is deprecated and has no function.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "BASIC",
                                    "desc": "Deprecated"
                                },
                                {
                                    "name": "FULL",
                                    "desc": "Deprecated"
                                }
                            ]
                        },
                        {
                            "name": "revisionId",
                            "desc": "Specifies the Revision ID that should be downloaded. Ignored unless alt=media is specified.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Insert a new file.",
                    "path": "files",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "timedTextLanguage",
                            "desc": "The language of the timed text.",
                            "type": "string"
                        },
                        {
                            "name": "timedTextTrackName",
                            "desc": "The timed text track name.",
                            "type": "string"
                        },
                        {
                            "name": "useContentAsIndexableText",
                            "desc": "Whether to use the content as indexable text.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "visibility",
                            "desc": "The visibility of the new file. This parameter is only relevant when convert=false.",
                            "type": "string",
                            "default": "DEFAULT",
                            "enum": [
                                {
                                    "name": "DEFAULT",
                                    "desc": "The visibility of the new file is determined by the user's default visibility/sharing policies."
                                },
                                {
                                    "name": "PRIVATE",
                                    "desc": "The new file will be visible to only the owner."
                                }
                            ]
                        },
                        {
                            "name": "convert",
                            "desc": "Whether to convert this file to the corresponding Google Docs format.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "ocr",
                            "desc": "Whether to attempt OCR on .jpg, .png, .gif, or .pdf uploads.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "ocrLanguage",
                            "desc": "If ocr is true, hints at the language to use. Valid values are BCP 47 codes.",
                            "type": "string"
                        },
                        {
                            "name": "pinned",
                            "desc": "Whether to pin the head revision of the uploaded file. A file can have a maximum of 200 pinned revisions.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates file metadata and/or content. This method supports patch semantics.",
                    "path": "files/{fileId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to update.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "addParents",
                            "desc": "Comma-separated list of parent IDs to add.",
                            "type": "string"
                        },
                        {
                            "name": "modifiedDateBehavior",
                            "desc": "Determines the behavior in which modifiedDate is updated. This overrides setModifiedDate.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "fromBody",
                                    "desc": "Set modifiedDate to the value provided in the body of the request. No change if no value was provided."
                                },
                                {
                                    "name": "fromBodyIfNeeded",
                                    "desc": "Set modifiedDate to the value provided in the body of the request depending on other contents of the update."
                                },
                                {
                                    "name": "fromBodyOrNow",
                                    "desc": "Set modifiedDate to the value provided in the body of the request, or to the current time if no value was provided."
                                },
                                {
                                    "name": "noChange",
                                    "desc": "Maintain the previous value of modifiedDate."
                                },
                                {
                                    "name": "now",
                                    "desc": "Set modifiedDate to the current time."
                                },
                                {
                                    "name": "nowIfNeeded",
                                    "desc": "Set modifiedDate to the current time depending on contents of the update."
                                }
                            ]
                        },
                        {
                            "name": "updateViewedDate",
                            "desc": "Whether to update the view date after successfully updating the file.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "ocr",
                            "desc": "Whether to attempt OCR on .jpg, .png, .gif, or .pdf uploads.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "pinned",
                            "desc": "Whether to pin the new revision. A file can have a maximum of 200 pinned revisions.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "setModifiedDate",
                            "desc": "Whether to set the modified date with the supplied modified date.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "timedTextLanguage",
                            "desc": "The language of the timed text.",
                            "type": "string"
                        },
                        {
                            "name": "convert",
                            "desc": "This parameter is deprecated and has no function.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "timedTextTrackName",
                            "desc": "The timed text track name.",
                            "type": "string"
                        },
                        {
                            "name": "newRevision",
                            "desc": "Whether a blob upload should create a new revision. If false, the blob data in the current head revision is replaced. If true or not set, a new blob is created as head revision, and previous unpinned revisions are preserved for a short period of time. Pinned revisions are stored indefinitely, using additional storage quota, up to a maximum of 200 revisions. For details on how revisions are retained, see the Drive Help Center.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "ocrLanguage",
                            "desc": "If ocr is true, hints at the language to use. Valid values are BCP 47 codes.",
                            "type": "string"
                        },
                        {
                            "name": "removeParents",
                            "desc": "Comma-separated list of parent IDs to remove.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "useContentAsIndexableText",
                            "desc": "Whether to use the content as indexable text.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists the user's files.",
                    "path": "files",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "corpus",
                            "desc": "The body of items (files/documents) to which the query applies. Deprecated: use 'corpora' instead.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "DEFAULT",
                                    "desc": "The items that the user has accessed."
                                },
                                {
                                    "name": "DOMAIN",
                                    "desc": "Items shared to the user's domain."
                                }
                            ]
                        },
                        {
                            "name": "includeTeamDriveItems",
                            "desc": "Whether Team Drive items should be included in results.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of files to return.",
                            "type": "int32",
                            "default": "100",
                            "min": "0"
                        },
                        {
                            "name": "orderBy",
                            "desc": "A comma-separated list of sort keys. Valid keys are 'createdDate', 'folder', 'lastViewedByMeDate', 'modifiedByMeDate', 'modifiedDate', 'quotaBytesUsed', 'recency', 'sharedWithMeDate', 'starred', and 'title'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedDate desc,title. Please note that there is a current limitation for users with approximately one million files in which the requested[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Page token for files.",
                            "type": "string"
                        },
                        {
                            "name": "projection",
                            "desc": "This parameter is deprecated and has no function.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "BASIC",
                                    "desc": "Deprecated"
                                },
                                {
                                    "name": "FULL",
                                    "desc": "Deprecated"
                                }
                            ]
                        },
                        {
                            "name": "q",
                            "desc": "Query string for searching files.",
                            "type": "string"
                        },
                        {
                            "name": "spaces",
                            "desc": "A comma-separated list of spaces to query. Supported values are 'drive', 'appDataFolder' and 'photos'.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "corpora",
                            "desc": "Comma-separated list of bodies of items (files/documents) to which the query applies. Supported bodies are 'default', 'domain', 'teamDrive' and 'allTeamDrives'. 'allTeamDrives' must be combined with 'default'; all other values must be used in isolation. Prefer 'default' or 'teamDrive' to 'allTeamDrives' for efficiency.",
                            "type": "string"
                        },
                        {
                            "name": "teamDriveId",
                            "desc": "ID of Team Drive to search.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "touch",
                    "desc": "Set the file's updated time to the current server time.",
                    "path": "files/{fileId}/touch",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to update.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "export",
                    "desc": "Exports a Google Doc to the requested MIME type and returns the exported content.",
                    "path": "files/{fileId}/export",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "mimeType",
                            "desc": "The MIME type of the format requested for this export.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "untrash",
                    "desc": "Restores a file from the trash.",
                    "path": "files/{fileId}/untrash",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to untrash.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "trash",
                    "desc": "Moves a file to the trash. The currently authenticated user must own the file or be an organizer on the parent for Team Drive files.",
                    "path": "files/{fileId}/trash",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to trash.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates file metadata and/or content.",
                    "path": "files/{fileId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file to update.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "setModifiedDate",
                            "desc": "Whether to set the modified date with the supplied modified date.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "timedTextLanguage",
                            "desc": "The language of the timed text.",
                            "type": "string"
                        },
                        {
                            "name": "timedTextTrackName",
                            "desc": "The timed text track name.",
                            "type": "string"
                        },
                        {
                            "name": "updateViewedDate",
                            "desc": "Whether to update the view date after successfully updating the file.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "convert",
                            "desc": "This parameter is deprecated and has no function.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "modifiedDateBehavior",
                            "desc": "Determines the behavior in which modifiedDate is updated. This overrides setModifiedDate.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "fromBody",
                                    "desc": "Set modifiedDate to the value provided in the body of the request. No change if no value was provided."
                                },
                                {
                                    "name": "fromBodyIfNeeded",
                                    "desc": "Set modifiedDate to the value provided in the body of the request depending on other contents of the update."
                                },
                                {
                                    "name": "fromBodyOrNow",
                                    "desc": "Set modifiedDate to the value provided in the body of the request, or to the current time if no value was provided."
                                },
                                {
                                    "name": "noChange",
                                    "desc": "Maintain the previous value of modifiedDate."
                                },
                                {
                                    "name": "now",
                                    "desc": "Set modifiedDate to the current time."
                                },
                                {
                                    "name": "nowIfNeeded",
                                    "desc": "Set modifiedDate to the current time depending on contents of the update."
                                }
                            ]
                        },
                        {
                            "name": "ocr",
                            "desc": "Whether to attempt OCR on .jpg, .png, .gif, or .pdf uploads.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "removeParents",
                            "desc": "Comma-separated list of parent IDs to remove.",
                            "type": "string"
                        },
                        {
                            "name": "addParents",
                            "desc": "Comma-separated list of parent IDs to add.",
                            "type": "string"
                        },
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "useContentAsIndexableText",
                            "desc": "Whether to use the content as indexable text.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "newRevision",
                            "desc": "Whether a blob upload should create a new revision. If false, the blob data in the current head revision is replaced. If true or not set, a new blob is created as head revision, and previous unpinned revisions are preserved for a short period of time. Pinned revisions are stored indefinitely, using additional storage quota, up to a maximum of 200 revisions. For details on how revisions are retained, see the Drive Help Center.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "pinned",
                            "desc": "Whether to pin the new revision. A file can have a maximum of 200 pinned revisions.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "ocrLanguage",
                            "desc": "If ocr is true, hints at the language to use. Valid values are BCP 47 codes.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "about",
            "methods": [
                {
                    "name": "get",
                    "desc": "Gets the information about the current user along with Drive API settings",
                    "path": "about",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeSubscribed",
                            "desc": "When calculating the number of remaining change IDs, whether to include public files the user has opened and shared files. When set to false, this counts only change IDs for owned files and any shared or public files that the user has explicitly added to a folder they own.",
                            "type": "bool",
                            "default": "true"
                        },
                        {
                            "name": "maxChangeIdCount",
                            "desc": "Maximum number of remaining change IDs to count",
                            "type": "int64",
                            "default": "1"
                        },
                        {
                            "name": "startChangeId",
                            "desc": "Change ID to start counting from when calculating number of remaining change IDs",
                            "type": "int64"
                        }
                    ]
                }
            ]
        },
        {
            "name": "comments",
            "methods": [
                {
                    "name": "patch",
                    "desc": "Updates an existing comment. This method supports patch semantics.",
                    "path": "files/{fileId}/comments/{commentId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates an existing comment.",
                    "path": "files/{fileId}/comments/{commentId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a comment.",
                    "path": "files/{fileId}/comments/{commentId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a comment by ID.",
                    "path": "files/{fileId}/comments/{commentId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "commentId",
                            "desc": "The ID of the comment.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeDeleted",
                            "desc": "If set, this will succeed when retrieving a deleted comment, and will include any deleted replies.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a new comment on the given file.",
                    "path": "files/{fileId}/comments",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a file's comments.",
                    "path": "files/{fileId}/comments",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "includeDeleted",
                            "desc": "If set, all comments and replies, including deleted comments and replies (with content stripped) will be returned.",
                            "type": "bool",
                            "default": "false"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maximum number of discussions to include in the response, used for paging.",
                            "type": "int32",
                            "default": "20",
                            "min": "0",
                            "max": "100"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The continuation token, used to page through large result sets. To get the next page of results, set this parameter to the value of \"nextPageToken\" from the previous response.",
                            "type": "string"
                        },
                        {
                            "name": "updatedMin",
                            "desc": "Only discussions that were updated after this timestamp will be returned. Formatted as an RFC 3339 timestamp.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "teamdrives",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Permanently deletes a Team Drive for which the user is an organizer. The Team Drive cannot contain any untrashed items.",
                    "path": "teamdrives/{teamDriveId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "pathParams": [
                        {
                            "name": "teamDriveId",
                            "desc": "The ID of the Team Drive",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a Team Drive's metadata by ID.",
                    "path": "teamdrives/{teamDriveId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "teamDriveId",
                            "desc": "The ID of the Team Drive",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a new Team Drive.",
                    "path": "teamdrives",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "requestId",
                            "desc": "An ID, such as a random UUID, which uniquely identifies this user's request for idempotent creation of a Team Drive. A repeated request by the same user and with the same request ID will avoid creating duplicates by attempting to create the same Team Drive. If the Team Drive already exists a 409 error will be returned.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists the user's Team Drives.",
                    "path": "teamdrives",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of Team Drives to return.",
                            "type": "int32",
                            "default": "10",
                            "min": "1",
                            "max": "100"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Page token for Team Drives.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a Team Drive's metadata",
                    "path": "teamdrives/{teamDriveId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "pathParams": [
                        {
                            "name": "teamDriveId",
                            "desc": "The ID of the Team Drive",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "apps",
            "methods": [
                {
                    "name": "get",
                    "desc": "Gets a specific app.",
                    "path": "apps/{appId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "appId",
                            "desc": "The ID of the app.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a user's installed apps.",
                    "path": "apps",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.apps.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "appFilterExtensions",
                            "desc": "A comma-separated list of file extensions for open with filtering. All apps within the given app query scope which can open any of the given file extensions will be included in the response. If appFilterMimeTypes are provided as well, the result is a union of the two resulting app lists.",
                            "type": "string"
                        },
                        {
                            "name": "appFilterMimeTypes",
                            "desc": "A comma-separated list of MIME types for open with filtering. All apps within the given app query scope which can open any of the given MIME types will be included in the response. If appFilterExtensions are provided as well, the result is a union of the two resulting app lists.",
                            "type": "string"
                        },
                        {
                            "name": "languageCode",
                            "desc": "A language or locale code, as defined by BCP 47, with some extensions from Unicode's LDML format (http://www.unicode.org/reports/tr35/).",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "channels",
            "methods": [
                {
                    "name": "stop",
                    "desc": "Stop watching resources through this channel",
                    "path": "channels/stop",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            ]
        },
        {
            "name": "children",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Removes a child from a folder.",
                    "path": "files/{folderId}/children/{childId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "folderId",
                            "desc": "The ID of the folder.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "childId",
                            "desc": "The ID of the child.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a specific child reference.",
                    "path": "files/{folderId}/children/{childId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "folderId",
                            "desc": "The ID of the folder.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "childId",
                            "desc": "The ID of the child.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Inserts a file into a folder.",
                    "path": "files/{folderId}/children",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "folderId",
                            "desc": "The ID of the folder.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a folder's children.",
                    "path": "files/{folderId}/children",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "folderId",
                            "desc": "The ID of the folder.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of children to return.",
                            "type": "int32",
                            "default": "100",
                            "min": "0"
                        },
                        {
                            "name": "orderBy",
                            "desc": "A comma-separated list of sort keys. Valid keys are 'createdDate', 'folder', 'lastViewedByMeDate', 'modifiedByMeDate', 'modifiedDate', 'quotaBytesUsed', 'recency', 'sharedWithMeDate', 'starred', and 'title'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedDate desc,title. Please note that there is a current limitation for users with approximately one million files in which the requested[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Page token for children.",
                            "type": "string"
                        },
                        {
                            "name": "q",
                            "desc": "Query string for searching children.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "parents",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Removes a parent from a file.",
                    "path": "files/{fileId}/parents/{parentId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "parentId",
                            "desc": "The ID of the parent.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a specific parent reference.",
                    "path": "files/{fileId}/parents/{parentId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "parentId",
                            "desc": "The ID of the parent.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a parent folder for a file.",
                    "path": "files/{fileId}/parents",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "supportsTeamDrives",
                            "desc": "Whether the requesting application supports Team Drives.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a file's parents.",
                    "path": "files/{fileId}/parents",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "properties",
            "methods": [
                {
                    "name": "update",
                    "desc": "Updates a property, or adds it if it doesn't exist.",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "propertyKey",
                            "desc": "The key of the property.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "visibility",
                            "desc": "The visibility of the property.",
                            "type": "string",
                            "default": "private"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a property.",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "propertyKey",
                            "desc": "The key of the property.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "visibility",
                            "desc": "The visibility of the property.",
                            "type": "string",
                            "default": "private"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Gets a property by its key.",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "propertyKey",
                            "desc": "The key of the property.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "visibility",
                            "desc": "The visibility of the property.",
                            "type": "string",
                            "default": "private"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a property to a file, or updates it if it already exists.",
                    "path": "files/{fileId}/properties",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists a file's properties.",
                    "path": "files/{fileId}/properties",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates a property, or adds it if it doesn't exist. This method supports patch semantics.",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "pathParams": [
                        {
                            "name": "fileId",
                            "desc": "The ID of the file.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "propertyKey",
                            "desc": "The key of the property.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "visibility",
                            "desc": "The visibility of the property.",
                            "type": "string",
                            "default": "private"
                        }
                    ]
                }
            ]
        }
    ]
}