{
    "kind": "discovery#restDescription",
    "etag": "\"tbys6C40o18GZwyMen5GMkdK-3s/QkjGIRroDT5nHgu1Wy3bp0C7GqA\"",
    "discoveryVersion": "v1",
    "id": "fusiontables:v2",
    "name": "fusiontables",
    "version": "v2",
    "title": "Fusion Tables API",
    "description": "API for working with Fusion Tables data.",
    "documentationLink": "https://developers.google.com/fusiontables",
    "protocol": "rest",
    "rootUrl": "https://www.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
        ]
    },
    "resources": [
        {
            "name": "column",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes the specified column.",
                    "path": "tables/{tableId}/columns/{columnId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table from which the column is being deleted.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "columnId",
                            "desc": "Name or identifier for the column being deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Retrieves a specific column by its ID.",
                    "path": "tables/{tableId}/columns/{columnId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the column belongs.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "columnId",
                            "desc": "Name or identifier for the column that is being requested.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a new column to the table.",
                    "path": "tables/{tableId}/columns",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table for which a new column is being added.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves a list of columns.",
                    "path": "tables/{tableId}/columns",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose columns are being listed.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of columns to return. Default is 5.",
                            "type": "uint32",
                            "min": "0"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Continuation token specifying which result page to return.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates the name or type of an existing column. This method supports patch semantics.",
                    "path": "tables/{tableId}/columns/{columnId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table for which the column is being updated.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "columnId",
                            "desc": "Name or identifier for the column that is being updated.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates the name or type of an existing column.",
                    "path": "tables/{tableId}/columns/{columnId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table for which the column is being updated.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "columnId",
                            "desc": "Name or identifier for the column that is being updated.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "query",
            "methods": [
                {
                    "name": "sql",
                    "desc": "Executes a Fusion Tables SQL statement, which can be any of \n- SELECT\n- INSERT\n- UPDATE\n- DELETE\n- SHOW\n- DESCRIBE\n- CREATE statement.",
                    "path": "query",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "sql",
                            "desc": "A Fusion Tables SQL statement, which can be any of \n- SELECT\n- INSERT\n- UPDATE\n- DELETE\n- SHOW\n- DESCRIBE\n- CREATE",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hdrs",
                            "desc": "Whether column names are included in the first row. Default is true.",
                            "type": "bool"
                        },
                        {
                            "name": "typed",
                            "desc": "Whether typed values are returned in the (JSON) response: numbers for numeric values and parsed geometries for KML values. Default is true.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "sqlGet",
                    "desc": "Executes a SQL statement which can be any of \n- SELECT\n- SHOW\n- DESCRIBE",
                    "path": "query",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "sql",
                            "desc": "A SQL statement which can be any of \n- SELECT\n- SHOW\n- DESCRIBE",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hdrs",
                            "desc": "Whether column names are included (in the first row). Default is true.",
                            "type": "bool"
                        },
                        {
                            "name": "typed",
                            "desc": "Whether typed values are returned in the (JSON) response: numbers for numeric values and parsed geometries for KML values. Default is true.",
                            "type": "bool"
                        }
                    ]
                }
            ]
        },
        {
            "name": "style",
            "methods": [
                {
                    "name": "get",
                    "desc": "Gets a specific style.",
                    "path": "tables/{tableId}/styles/{styleId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the requested style belongs",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "styleId",
                            "desc": "Identifier (integer) for a specific style in a table",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a new style for the table.",
                    "path": "tables/{tableId}/styles",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table for which a new style is being added",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves a list of styles.",
                    "path": "tables/{tableId}/styles",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose styles are being listed",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of styles to return. Optional. Default is 5.",
                            "type": "uint32",
                            "min": "0"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Continuation token specifying which result page to return. Optional.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates an existing style. This method supports patch semantics.",
                    "path": "tables/{tableId}/styles/{styleId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose style is being updated.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "styleId",
                            "desc": "Identifier (within a table) for the style being updated.",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates an existing style.",
                    "path": "tables/{tableId}/styles/{styleId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose style is being updated.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "styleId",
                            "desc": "Identifier (within a table) for the style being updated.",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a style.",
                    "path": "tables/{tableId}/styles/{styleId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table from which the style is being deleted",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "styleId",
                            "desc": "Identifier (within a table) for the style being deleted",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                }
            ]
        },
        {
            "name": "table",
            "methods": [
                {
                    "name": "get",
                    "desc": "Retrieves a specific table by its ID.",
                    "path": "tables/{tableId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Identifier for the table being requested.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "importRows",
                    "desc": "Imports more rows into a table.",
                    "path": "tables/{tableId}/import",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "The table into which new rows are being imported.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "delimiter",
                            "desc": "The delimiter used to separate cell values. This can only consist of a single character. Default is ,.",
                            "type": "string"
                        },
                        {
                            "name": "encoding",
                            "desc": "The encoding of the content. Default is UTF-8. Use auto-detect if you are unsure of the encoding.",
                            "type": "string"
                        },
                        {
                            "name": "endLine",
                            "desc": "The index of the line up to which data will be imported. Default is to import the entire file. If endLine is negative, it is an offset from the end of the file; the imported content will exclude the last endLine lines.",
                            "type": "int32"
                        },
                        {
                            "name": "isStrict",
                            "desc": "Whether the imported CSV must have the same number of values for each row. If false, rows with fewer values will be padded with empty values. Default is true.",
                            "type": "bool"
                        },
                        {
                            "name": "startLine",
                            "desc": "The index of the first line from which to start importing, inclusive. Default is 0.",
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "importTable",
                    "desc": "Imports a new table.",
                    "path": "tables/import",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "name",
                            "desc": "The name to be assigned to the new table.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "delimiter",
                            "desc": "The delimiter used to separate cell values. This can only consist of a single character. Default is ,.",
                            "type": "string"
                        },
                        {
                            "name": "encoding",
                            "desc": "The encoding of the content. Default is UTF-8. Use auto-detect if you are unsure of the encoding.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a new table.",
                    "path": "tables",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves a list of tables a user owns.",
                    "path": "tables",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of tables to return. Default is 5.",
                            "type": "uint32",
                            "min": "0"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Continuation token specifying which result page to return.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "replaceRows",
                    "desc": "Replaces rows of an existing table. Current rows remain visible until all replacement rows are ready.",
                    "path": "tables/{tableId}/replace",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose rows will be replaced.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "delimiter",
                            "desc": "The delimiter used to separate cell values. This can only consist of a single character. Default is ,.",
                            "type": "string"
                        },
                        {
                            "name": "encoding",
                            "desc": "The encoding of the content. Default is UTF-8. Use 'auto-detect' if you are unsure of the encoding.",
                            "type": "string"
                        },
                        {
                            "name": "endLine",
                            "desc": "The index of the line up to which data will be imported. Default is to import the entire file. If endLine is negative, it is an offset from the end of the file; the imported content will exclude the last endLine lines.",
                            "type": "int32"
                        },
                        {
                            "name": "isStrict",
                            "desc": "Whether the imported CSV must have the same number of column values for each row. If true, throws an exception if the CSV does not have the same number of columns. If false, rows with fewer column values will be padded with empty values. Default is true.",
                            "type": "bool"
                        },
                        {
                            "name": "startLine",
                            "desc": "The index of the first line from which to start importing, inclusive. Default is 0.",
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a table.",
                    "path": "tables/{tableId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "ID of the table to be deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated. This method supports patch semantics.",
                    "path": "tables/{tableId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "ID of the table that is being updated.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "replaceViewDefinition",
                            "desc": "Whether the view definition is also updated. The specified view definition replaces the existing one. Only a view can be updated with a new definition.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated.",
                    "path": "tables/{tableId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "ID of the table that is being updated.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "replaceViewDefinition",
                            "desc": "Whether the view definition is also updated. The specified view definition replaces the existing one. Only a view can be updated with a new definition.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "copy",
                    "desc": "Copies a table.",
                    "path": "tables/{tableId}/copy",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "ID of the table that is being copied.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "copyPresentation",
                            "desc": "Whether to also copy tabs, styles, and templates. Default is false.",
                            "type": "bool"
                        }
                    ]
                }
            ]
        },
        {
            "name": "task",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a specific task by its ID, unless that task has already started running.",
                    "path": "tables/{tableId}/tasks/{taskId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table from which the task is being deleted.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "taskId",
                            "desc": "The identifier of the task to delete.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Retrieves a specific task by its ID.",
                    "path": "tables/{tableId}/tasks/{taskId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the task belongs.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "taskId",
                            "desc": "The identifier of the task to get.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves a list of tasks.",
                    "path": "tables/{tableId}/tasks",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table whose tasks are being listed.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "pageToken",
                            "desc": "Continuation token specifying which result page to return.",
                            "type": "string"
                        },
                        {
                            "name": "startIndex",
                            "desc": "Index of the first result returned in the current page.",
                            "type": "uint32"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of tasks to return. Default is 5.",
                            "type": "uint32",
                            "min": "0"
                        }
                    ]
                }
            ]
        },
        {
            "name": "template",
            "methods": [
                {
                    "name": "insert",
                    "desc": "Creates a new template for the table.",
                    "path": "tables/{tableId}/templates",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table for which a new template is being created",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves a list of templates.",
                    "path": "tables/{tableId}/templates",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Identifier for the table whose templates are being requested",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "pageToken",
                            "desc": "Continuation token specifying which results page to return. Optional.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Maximum number of templates to return. Optional. Default is 5.",
                            "type": "uint32",
                            "min": "0"
                        }
                    ]
                },
                {
                    "name": "patch",
                    "desc": "Updates an existing template. This method supports patch semantics.",
                    "path": "tables/{tableId}/templates/{templateId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the updated template belongs",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "templateId",
                            "desc": "Identifier for the template that is being updated",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates an existing template",
                    "path": "tables/{tableId}/templates/{templateId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the updated template belongs",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "templateId",
                            "desc": "Identifier for the template that is being updated",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a template",
                    "path": "tables/{tableId}/templates/{templateId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table from which the template is being deleted",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "templateId",
                            "desc": "Identifier for the template which is being deleted",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Retrieves a specific template by its id",
                    "path": "tables/{tableId}/templates/{templateId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/fusiontables",
                        "https://www.googleapis.com/auth/fusiontables.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "tableId",
                            "desc": "Table to which the template belongs",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "templateId",
                            "desc": "Identifier for the template that is being requested",
                            "required": true,
                            "type": "int32"
                        }
                    ]
                }
            ]
        }
    ]
}