{
    "kind": "discovery#restDescription",
    "etag": "\"tbys6C40o18GZwyMen5GMkdK-3s/f81k8b4sv9uLeywfoj2KpL2xcPg\"",
    "discoveryVersion": "v1",
    "id": "youtube:v3",
    "name": "youtube",
    "version": "v3",
    "title": "YouTube Data API",
    "description": "Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.",
    "documentationLink": "https://developers.google.com/youtube/v3",
    "protocol": "rest",
    "rootUrl": "https://www.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/youtubepartner-channel-audit",
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
        ]
    },
    "resources": [
        {
            "name": "channelSections",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a channelSection.",
                    "path": "channelSections",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube channelSection ID for the resource that is being deleted. In a channelSection resource, the id property specifies the YouTube channelSection ID.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a channelSection for the authenticated user's channel.",
                    "path": "channelSections",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part names that you can include in the parameter value are snippet and contentDetails.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns channelSection resources that match the API request criteria.",
                    "path": "channelSections",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more channelSection resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, and contentDetails.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a channelSection resource, the snippet property contains other properties, such as a[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter specifies a YouTube channel ID. The API will only return that channel's channelSections.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter indicates that the snippet.localized property values in the returned channelSection resources should be in the specified language if localized values for that language are available. For example, if the API request specifies hl=de, the snippet.localized properties in the API response will contain German titles if German titles are available. Channel owners can provide localized channel section titles using either the channelSections.insert or[...]",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube channelSection ID(s) for the resource(s) that are being retrieved. In a channelSection resource, the id property specifies the YouTube channelSection ID.",
                            "type": "string"
                        },
                        {
                            "name": "mine",
                            "desc": "Set this parameter's value to true to retrieve a feed of the authenticated user's channelSections.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Update a channelSection.",
                    "path": "channelSections",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part names that you can include in the parameter value are snippet and contentDetails.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "activities",
            "methods": [
                {
                    "name": "insert",
                    "desc": "Posts a bulletin for a specific channel. (The user submitting the request must be authorized to act on the channel's behalf.)\n\nNote: Even though an activity resource can contain information about actions like a user rating a video or marking a video as a favorite, you need to use other API methods to generate those activity resources. For example, you would use the API's videos.rate() method to rate a video and the playlistItems.insert() method to mark a video as a[...]",
                    "path": "activities",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a list of channel activity events that match the request criteria. For example, you can retrieve events associated with a particular channel, events associated with the user's subscriptions and Google+ friends, or the YouTube home page feed, which is customized for each user.",
                    "path": "activities",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more activity resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in an activity resource, the snippet property contains other properties that identify the type of activity, a display title for the activity, and so forth. If you set part=snippet, the API [...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "mine",
                            "desc": "Set this parameter's value to true to retrieve a feed of the authenticated user's activities.",
                            "type": "bool"
                        },
                        {
                            "name": "publishedAfter",
                            "desc": "The publishedAfter parameter specifies the earliest date and time that an activity could have occurred for that activity to be included in the API response. If the parameter value specifies a day, but not a time, then any activities that occurred that day will be included in the result set. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format.",
                            "type": "datetime"
                        },
                        {
                            "name": "regionCode",
                            "desc": "The regionCode parameter instructs the API to return results for the specified country. The parameter value is an ISO 3166-1 alpha-2 country code. YouTube uses this value when the authorized user's previous activity on YouTube does not provide enough information to generate the activity feed.",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "publishedBefore",
                            "desc": "The publishedBefore parameter specifies the date and time before which an activity must have occurred for that activity to be included in the API response. If the parameter value specifies a day, but not a time, then any activities that occurred that day will be excluded from the result set. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format.",
                            "type": "datetime"
                        },
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter specifies a unique YouTube channel ID. The API will then return a list of that channel's activities.",
                            "type": "string"
                        },
                        {
                            "name": "home",
                            "desc": "Set this parameter's value to true to retrieve the activity feed that displays on the YouTube home page for the currently authenticated user.",
                            "type": "bool"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        }
                    ]
                }
            ]
        },
        {
            "name": "fanFundingEvents",
            "methods": [
                {
                    "name": "list",
                    "desc": "Lists fan funding events for a channel.",
                    "path": "fanFundingEvents",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the fanFundingEvent resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter instructs the API to retrieve localized resource metadata for a specific application language that the YouTube website supports. The parameter value must be a language code included in the list returned by the i18nLanguages.list method.\n\nIf localized resource details are available in that language, the resource's snippet.localized object will contain the localized values. However, if localized details are not available, the snippet.localize[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "guideCategories",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of categories that can be associated with YouTube channels.",
                    "path": "guideCategories",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the guideCategory resource properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "regionCode",
                            "desc": "The regionCode parameter instructs the API to return the list of guide categories available in the specified country. The parameter value is an ISO 3166-1 alpha-2 country code.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter specifies the language that will be used for text values in the API response.",
                            "type": "string",
                            "default": "en-US"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube channel category ID(s) for the resource(s) that are being retrieved. In a guideCategory resource, the id property specifies the YouTube channel category ID.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "sponsors",
            "methods": [
                {
                    "name": "list",
                    "desc": "Lists sponsors for a channel.",
                    "path": "sponsors",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the sponsor resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "filter",
                            "desc": "The filter parameter specifies which channel sponsors to return.",
                            "type": "string",
                            "default": "POLL_NEWEST",
                            "enum": [
                                {
                                    "name": "all",
                                    "desc": "Return all sponsors, from newest to oldest."
                                },
                                {
                                    "name": "newest",
                                    "desc": "Return the most recent sponsors, from newest to oldest."
                                }
                            ]
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "subscriptions",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a subscription.",
                    "path": "subscriptions",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube subscription ID for the resource that is being deleted. In a subscription resource, the id property specifies the YouTube subscription ID.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a subscription for the authenticated user's channel.",
                    "path": "subscriptions",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns subscription resources that match the API request criteria.",
                    "path": "subscriptions",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more subscription resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a subscription resource, the snippet property contains other properties, such as a display title for the subscription. If you set part=snippet, the API response will also contain all[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube subscription ID(s) for the resource(s) that are being retrieved. In a subscription resource, the id property specifies the YouTube subscription ID.",
                            "type": "string"
                        },
                        {
                            "name": "mine",
                            "desc": "Set this parameter's value to true to retrieve a feed of the authenticated user's subscriptions.",
                            "type": "bool"
                        },
                        {
                            "name": "myRecentSubscribers",
                            "desc": "Set this parameter's value to true to retrieve a feed of the subscribers of the authenticated user in reverse chronological order (newest first).",
                            "type": "bool"
                        },
                        {
                            "name": "order",
                            "desc": "The order parameter specifies the method that will be used to sort resources in the API response.",
                            "type": "string",
                            "default": "SUBSCRIPTION_ORDER_RELEVANCE",
                            "enum": [
                                {
                                    "name": "alphabetical",
                                    "desc": "Sort alphabetically."
                                },
                                {
                                    "name": "relevance",
                                    "desc": "Sort by relevance."
                                },
                                {
                                    "name": "unread",
                                    "desc": "Sort by order of activity."
                                }
                            ]
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter specifies a YouTube channel ID. The API will only return that channel's subscriptions.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "mySubscribers",
                            "desc": "Set this parameter's value to true to retrieve a feed of the subscribers of the authenticated user in no particular order.",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "forChannelId",
                            "desc": "The forChannelId parameter specifies a comma-separated list of channel IDs. The API response will then only contain subscriptions matching those channels.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "thumbnails",
            "methods": [
                {
                    "name": "set",
                    "desc": "Uploads a custom video thumbnail to YouTube and sets it for a video.",
                    "path": "thumbnails/set",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "videoId",
                            "desc": "The videoId parameter specifies a YouTube video ID for which the custom video thumbnail is being provided.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "playlistItems",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a playlist item.",
                    "path": "playlistItems",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube playlist item ID for the playlist item that is being deleted. In a playlistItem resource, the id property specifies the playlist item's ID.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a resource to a playlist.",
                    "path": "playlistItems",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a collection of playlist items that match the API request parameters. You can retrieve all of the playlist items in a specified playlist or retrieve one or more playlist items by their unique IDs.",
                    "path": "playlistItems",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more playlistItem resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a playlistItem resource, the snippet property contains numerous fields, including the title, description, position, and resourceId properties. As such, if you set part=snippet, the A[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "videoId",
                            "desc": "The videoId parameter specifies that the request should return only the playlist items that contain the specified video.",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of one or more unique playlist item IDs.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "playlistId",
                            "desc": "The playlistId parameter specifies the unique ID of the playlist for which you want to retrieve playlist items. Note that even though this is an optional parameter, every request to retrieve playlist items must specify a value for either the id parameter or the playlistId parameter.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Modifies a playlist item. For example, you could update the item's position in the playlist.",
                    "path": "playlistItems",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nNote that this method will override the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. For example, a playlist item can specify a start time and end time, which identify the times portion of the video that [...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "search",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a collection of search results that match the query parameters specified in the API request. By default, a search result set identifies matching video, channel, and playlist resources, but you can also configure queries to only retrieve a specific type of resource.",
                    "path": "search",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more search resource properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "regionCode",
                            "desc": "The regionCode parameter instructs the API to return search results for the specified country. The parameter value is an ISO 3166-1 alpha-2 country code.",
                            "type": "string"
                        },
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter indicates that the API response should only contain resources created by the channel",
                            "type": "string"
                        },
                        {
                            "name": "forContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe forContentOwner parameter restricts the search to only retrieve resources owned by the content owner specified by the onBehalfOfContentOwner parameter. The user must be authenticated using a CMS account linked to the specified content owner and onBehalfOfContentOwner must be provided.",
                            "type": "bool"
                        },
                        {
                            "name": "q",
                            "desc": "The q parameter specifies the query term to search for.\n\nYour request can also use the Boolean NOT (-) and OR (|) operators to exclude videos or to find videos that are associated with one of several search terms. For example, to search for videos matching either \"boating\" or \"sailing\", set the q parameter value to boating|sailing. Similarly, to search for videos matching either \"boating\" or \"sailing\" but not \"fishing\", set the q parameter value t[...]",
                            "type": "string"
                        },
                        {
                            "name": "videoDimension",
                            "desc": "The videoDimension parameter lets you restrict a search to only retrieve 2D or 3D videos. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "2d",
                                    "desc": "Restrict search results to exclude 3D videos."
                                },
                                {
                                    "name": "3d",
                                    "desc": "Restrict search results to only include 3D videos."
                                },
                                {
                                    "name": "any",
                                    "desc": "Include both 3D and non-3D videos in returned results. This is the default value."
                                }
                            ]
                        },
                        {
                            "name": "publishedAfter",
                            "desc": "The publishedAfter parameter indicates that the API response should only contain resources created after the specified time. The value is an RFC 3339 formatted date-time value (1970-01-01T00:00:00Z).",
                            "type": "datetime"
                        },
                        {
                            "name": "relevanceLanguage",
                            "desc": "The relevanceLanguage parameter instructs the API to return search results that are most relevant to the specified language. The parameter value is typically an ISO 639-1 two-letter language code. However, you should use the values zh-Hans for simplified Chinese and zh-Hant for traditional Chinese. Please note that results in other languages will still be returned if they are highly relevant to the search query term.",
                            "type": "string"
                        },
                        {
                            "name": "forDeveloper",
                            "desc": "The forDeveloper parameter restricts the search to only retrieve videos uploaded via the developer's application or website. The API server uses the request's authorization credentials to identify the developer. Therefore, a developer can restrict results to videos uploaded through the developer's own app or website but not to videos uploaded through other apps or sites.",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "publishedBefore",
                            "desc": "The publishedBefore parameter indicates that the API response should only contain resources created before the specified time. The value is an RFC 3339 formatted date-time value (1970-01-01T00:00:00Z).",
                            "type": "datetime"
                        },
                        {
                            "name": "type",
                            "desc": "The type parameter restricts a search query to only retrieve a particular type of resource. The value is a comma-separated list of resource types.",
                            "type": "string",
                            "default": "video,channel,playlist"
                        },
                        {
                            "name": "videoEmbeddable",
                            "desc": "The videoEmbeddable parameter lets you to restrict a search to only videos that can be embedded into a webpage. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all videos, embeddable or not."
                                },
                                {
                                    "name": "true",
                                    "desc": "Only retrieve embeddable videos."
                                }
                            ]
                        },
                        {
                            "name": "forMine",
                            "desc": "The forMine parameter restricts the search to only retrieve videos owned by the authenticated user. If you set this parameter to true, then the type parameter's value must also be set to video.",
                            "type": "bool"
                        },
                        {
                            "name": "videoLicense",
                            "desc": "The videoLicense parameter filters search results to only include videos with a particular license. YouTube lets video uploaders choose to attach either the Creative Commons license or the standard YouTube license to each of their videos. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all videos, regardless of which license they have, that match the query parameters."
                                },
                                {
                                    "name": "creativeCommon",
                                    "desc": "Only return videos that have a Creative Commons license. Users can reuse videos with this license in other videos that they create. Learn more."
                                },
                                {
                                    "name": "youtube",
                                    "desc": "Only return videos that have the standard YouTube license."
                                }
                            ]
                        },
                        {
                            "name": "location",
                            "desc": "The location parameter, in conjunction with the locationRadius parameter, defines a circular geographic area and also restricts a search to videos that specify, in their metadata, a geographic location that falls within that area. The parameter value is a string that specifies latitude/longitude coordinates e.g. (37.42307,-122.08427).\n\n\n- The location parameter value identifies the point at the center of the area.\n- The locationRadius parameter specifies [...]",
                            "type": "string"
                        },
                        {
                            "name": "locationRadius",
                            "desc": "The locationRadius parameter, in conjunction with the location parameter, defines a circular geographic area.\n\nThe parameter value must be a floating point number followed by a measurement unit. Valid measurement units are m, km, ft, and mi. For example, valid parameter values include 1500m, 5km, 10000ft, and 0.75mi. The API does not support locationRadius parameter values larger than 1000 kilometers.\n\nNote: See the definition of the location parameter fo[...]",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "safeSearch",
                            "desc": "The safeSearch parameter indicates whether the search results should include restricted content as well as standard content.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "moderate",
                                    "desc": "YouTube will filter some content from search results and, at the least, will filter content that is restricted in your locale. Based on their content, search results could be removed from search results or demoted in search results. This is the default parameter value."
                                },
                                {
                                    "name": "none",
                                    "desc": "YouTube will not filter the search result set."
                                },
                                {
                                    "name": "strict",
                                    "desc": "YouTube will try to exclude all restricted content from the search result set. Based on their content, search results could be removed from search results or demoted in search results."
                                }
                            ]
                        },
                        {
                            "name": "topicId",
                            "desc": "The topicId parameter indicates that the API response should only contain resources associated with the specified topic. The value identifies a Freebase topic ID.",
                            "type": "string"
                        },
                        {
                            "name": "eventType",
                            "desc": "The eventType parameter restricts a search to broadcast events. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "completed",
                                    "desc": "Only include completed broadcasts."
                                },
                                {
                                    "name": "live",
                                    "desc": "Only include active broadcasts."
                                },
                                {
                                    "name": "upcoming",
                                    "desc": "Only include upcoming broadcasts."
                                }
                            ]
                        },
                        {
                            "name": "order",
                            "desc": "The order parameter specifies the method that will be used to order resources in the API response.",
                            "type": "string",
                            "default": "SEARCH_SORT_RELEVANCE",
                            "enum": [
                                {
                                    "name": "date",
                                    "desc": "Resources are sorted in reverse chronological order based on the date they were created."
                                },
                                {
                                    "name": "rating",
                                    "desc": "Resources are sorted from highest to lowest rating."
                                },
                                {
                                    "name": "relevance",
                                    "desc": "Resources are sorted based on their relevance to the search query. This is the default value for this parameter."
                                },
                                {
                                    "name": "title",
                                    "desc": "Resources are sorted alphabetically by title."
                                },
                                {
                                    "name": "videoCount",
                                    "desc": "Channels are sorted in descending order of their number of uploaded videos."
                                },
                                {
                                    "name": "viewCount",
                                    "desc": "Resources are sorted from highest to lowest number of views."
                                }
                            ]
                        },
                        {
                            "name": "relatedToVideoId",
                            "desc": "The relatedToVideoId parameter retrieves a list of videos that are related to the video that the parameter value identifies. The parameter value must be set to a YouTube video ID and, if you are using this parameter, the type parameter must be set to video.",
                            "type": "string"
                        },
                        {
                            "name": "videoCategoryId",
                            "desc": "The videoCategoryId parameter filters video search results based on their category. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string"
                        },
                        {
                            "name": "videoDefinition",
                            "desc": "The videoDefinition parameter lets you restrict a search to only include either high definition (HD) or standard definition (SD) videos. HD videos are available for playback in at least 720p, though higher resolutions, like 1080p, might also be available. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all videos, regardless of their resolution."
                                },
                                {
                                    "name": "high",
                                    "desc": "Only retrieve HD videos."
                                },
                                {
                                    "name": "standard",
                                    "desc": "Only retrieve videos in standard definition."
                                }
                            ]
                        },
                        {
                            "name": "videoDuration",
                            "desc": "The videoDuration parameter filters video search results based on their duration. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Do not filter video search results based on their duration. This is the default value."
                                },
                                {
                                    "name": "long",
                                    "desc": "Only include videos longer than 20 minutes."
                                },
                                {
                                    "name": "medium",
                                    "desc": "Only include videos that are between four and 20 minutes long (inclusive)."
                                },
                                {
                                    "name": "short",
                                    "desc": "Only include videos that are less than four minutes long."
                                }
                            ]
                        },
                        {
                            "name": "videoSyndicated",
                            "desc": "The videoSyndicated parameter lets you to restrict a search to only videos that can be played outside youtube.com. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all videos, syndicated or not."
                                },
                                {
                                    "name": "true",
                                    "desc": "Only retrieve syndicated videos."
                                }
                            ]
                        },
                        {
                            "name": "videoType",
                            "desc": "The videoType parameter lets you restrict a search to a particular type of videos. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all videos."
                                },
                                {
                                    "name": "episode",
                                    "desc": "Only retrieve episodes of shows."
                                },
                                {
                                    "name": "movie",
                                    "desc": "Only retrieve movies."
                                }
                            ]
                        },
                        {
                            "name": "channelType",
                            "desc": "The channelType parameter lets you restrict a search to a particular type of channel.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Return all channels."
                                },
                                {
                                    "name": "show",
                                    "desc": "Only retrieve shows."
                                }
                            ]
                        },
                        {
                            "name": "videoCaption",
                            "desc": "The videoCaption parameter indicates whether the API should filter video search results based on whether they have captions. If you specify a value for this parameter, you must also set the type parameter's value to video.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "any",
                                    "desc": "Do not filter results based on caption availability."
                                },
                                {
                                    "name": "closedCaption",
                                    "desc": "Only include videos that have captions."
                                },
                                {
                                    "name": "none",
                                    "desc": "Only include videos that do not have captions."
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "videoAbuseReportReasons",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of abuse reasons that can be used for reporting abusive videos.",
                    "path": "videoAbuseReportReasons",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the videoCategory resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hl",
                            "desc": "The hl parameter specifies the language that should be used for text values in the API response.",
                            "type": "string",
                            "default": "en_US"
                        }
                    ]
                }
            ]
        },
        {
            "name": "channels",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a collection of zero or more channel resources that match the request criteria.",
                    "path": "channels",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner",
                        "https://www.googleapis.com/auth/youtubepartner-channel-audit"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more channel resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a channel resource, the contentDetails property contains other properties, such as the uploads properties. As such, if you set part=contentDetails, the API response will also contain all [...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "forUsername",
                            "desc": "The forUsername parameter specifies a YouTube username, thereby requesting the channel associated with that username.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter should be used for filter out the properties that are not in the given language. Used for the brandingSettings part.",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube channel ID(s) for the resource(s) that are being retrieved. In a channel resource, the id property specifies the channel's YouTube channel ID.",
                            "type": "string"
                        },
                        {
                            "name": "managedByMe",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nSet this parameter's value to true to instruct the API to only return channels managed by the content owner that the onBehalfOfContentOwner parameter specifies. The user must be authenticated as a CMS account linked to the specified content owner and onBehalfOfContentOwner must be provided.",
                            "type": "bool"
                        },
                        {
                            "name": "mine",
                            "desc": "Set this parameter's value to true to instruct the API to only return channels owned by the authenticated user.",
                            "type": "bool"
                        },
                        {
                            "name": "mySubscribers",
                            "desc": "Use the subscriptions.list method and its mySubscribers parameter to retrieve a list of subscribers to the authenticated user's channel.",
                            "type": "bool"
                        },
                        {
                            "name": "categoryId",
                            "desc": "The categoryId parameter specifies a YouTube guide category, thereby requesting YouTube channels associated with that category.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a channel's metadata. Note that this method currently only supports updates to the channel resource's brandingSettings and invideoPromotion objects and their child properties.",
                    "path": "channels",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe API currently only allows the parameter value to be set to either brandingSettings or invideoPromotion. (You cannot update both of those parts with a single request.)\n\nNote that this method overrides the existing values for all of the mutable properties that are containe[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "The onBehalfOfContentOwner parameter indicates that the authenticated user is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their video and channel data, without having to provide authentication credentials for each individual channel. The actual CMS account t[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "commentThreads",
            "methods": [
                {
                    "name": "insert",
                    "desc": "Creates a new top-level comment. To add a reply to an existing comment, use the comments.insert method instead.",
                    "path": "commentThreads",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter identifies the properties that the API response will include. Set the parameter value to snippet. The snippet part has a quota cost of 2 units.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a list of comment threads that match the API request parameters.",
                    "path": "commentThreads",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more commentThread resource properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken property identifies the next page of the result that can be retrieved.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "string"
                        },
                        {
                            "name": "searchTerms",
                            "desc": "The searchTerms parameter instructs the API to limit the API response to only contain comments that contain the specified search terms.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "string"
                        },
                        {
                            "name": "allThreadsRelatedToChannelId",
                            "desc": "The allThreadsRelatedToChannelId parameter instructs the API to return all comment threads associated with the specified channel. The response can include comments about the channel or about the channel's videos.",
                            "type": "string"
                        },
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter instructs the API to return comment threads containing comments about the specified channel. (The response will not include comments left on videos that the channel uploaded.)",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of comment thread IDs for the resources that should be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "uint32",
                            "default": "20",
                            "min": "1",
                            "max": "100"
                        },
                        {
                            "name": "moderationStatus",
                            "desc": "Set this parameter to limit the returned comment threads to a particular moderation state.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "string",
                            "default": "MODERATION_STATUS_PUBLISHED",
                            "enum": [
                                {
                                    "name": "heldForReview",
                                    "desc": "Retrieve comment threads that are awaiting review by a moderator. A comment thread can be included in the response if the top-level comment or at least one of the replies to that comment are awaiting review."
                                },
                                {
                                    "name": "likelySpam",
                                    "desc": "Retrieve comment threads classified as likely to be spam. A comment thread can be included in the response if the top-level comment or at least one of the replies to that comment is considered likely to be spam."
                                },
                                {
                                    "name": "published",
                                    "desc": "Retrieve threads of published comments. This is the default value. A comment thread can be included in the response if its top-level comment has been published."
                                }
                            ]
                        },
                        {
                            "name": "order",
                            "desc": "The order parameter specifies the order in which the API response should list comment threads. Valid values are: \n- time - Comment threads are ordered by time. This is the default behavior.\n- relevance - Comment threads are ordered by relevance.Note: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "string",
                            "default": "true",
                            "enum": [
                                {
                                    "name": "relevance",
                                    "desc": "Order by relevance."
                                },
                                {
                                    "name": "time",
                                    "desc": "Order by time."
                                }
                            ]
                        },
                        {
                            "name": "textFormat",
                            "desc": "Set this parameter's value to html or plainText to instruct the API to return the comments left by users in html formatted or in plain text.",
                            "type": "string",
                            "default": "FORMAT_HTML",
                            "enum": [
                                {
                                    "name": "html",
                                    "desc": "Returns the comments in HTML format. This is the default value."
                                },
                                {
                                    "name": "plainText",
                                    "desc": "Returns the comments in plain text format."
                                }
                            ]
                        },
                        {
                            "name": "videoId",
                            "desc": "The videoId parameter instructs the API to return comment threads associated with the specified video ID.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Modifies the top-level comment in a comment thread.",
                    "path": "commentThreads",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of commentThread resource properties that the API response will include. You must at least include the snippet part in the parameter value since that part contains all of the properties that the API request can update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "comments",
            "methods": [
                {
                    "name": "update",
                    "desc": "Modifies a comment.",
                    "path": "comments",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter identifies the properties that the API response will include. You must at least include the snippet part in the parameter value since that part contains all of the properties that the API request can update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a comment.",
                    "path": "comments",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the comment ID for the resource that is being deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a reply to an existing comment. Note: To create a top-level comment, use the commentThreads.insert method.",
                    "path": "comments",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter identifies the properties that the API response will include. Set the parameter value to snippet. The snippet part has a quota cost of 2 units.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a list of comments that match the API request parameters.",
                    "path": "comments",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more comment resource properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "textFormat",
                            "desc": "This parameter indicates whether the API should return comments formatted as HTML or as plain text.",
                            "type": "string",
                            "default": "FORMAT_HTML",
                            "enum": [
                                {
                                    "name": "html",
                                    "desc": "Returns the comments in HTML format. This is the default value."
                                },
                                {
                                    "name": "plainText",
                                    "desc": "Returns the comments in plain text format."
                                }
                            ]
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of comment IDs for the resources that are being retrieved. In a comment resource, the id property specifies the comment's ID.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "uint32",
                            "default": "20",
                            "min": "1",
                            "max": "100"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken property identifies the next page of the result that can be retrieved.\n\nNote: This parameter is not supported for use in conjunction with the id parameter.",
                            "type": "string"
                        },
                        {
                            "name": "parentId",
                            "desc": "The parentId parameter specifies the ID of the comment for which replies should be retrieved.\n\nNote: YouTube currently supports replies only for top-level comments. However, replies to replies may be supported in the future.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "markAsSpam",
                    "desc": "Expresses the caller's opinion that one or more comments should be flagged as spam.",
                    "path": "comments/markAsSpam",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of IDs of comments that the caller believes should be classified as spam.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "setModerationStatus",
                    "desc": "Sets the moderation status of one or more comments. The API request must be authorized by the owner of the channel or video associated with the comments.",
                    "path": "comments/setModerationStatus",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of IDs that identify the comments for which you are updating the moderation status.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "moderationStatus",
                            "desc": "Identifies the new moderation status of the specified comments.",
                            "required": true,
                            "type": "string",
                            "enum": [
                                {
                                    "name": "heldForReview",
                                    "desc": "Marks a comment as awaiting review by a moderator."
                                },
                                {
                                    "name": "published",
                                    "desc": "Clears a comment for public display."
                                },
                                {
                                    "name": "rejected",
                                    "desc": "Rejects a comment as being unfit for display. This action also effectively hides all replies to the rejected comment.\n\nNote: The API does not currently provide a way to list or otherwise discover rejected comments. However, you can change the moderation status of a rejected comment if you still know its ID. If you were to change the moderation status of a rejected comment, the comment replies would subsequently be discoverable again as well."
                                }
                            ]
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "banAuthor",
                            "desc": "The banAuthor parameter lets you indicate that you want to automatically reject any additional comments written by the comment's author. Set the parameter value to true to ban the author.\n\nNote: This parameter is only valid if the moderationStatus parameter is also set to rejected.",
                            "type": "bool",
                            "default": "false"
                        }
                    ]
                }
            ]
        },
        {
            "name": "liveStreams",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of video streams that match the API request parameters.",
                    "path": "liveStreams",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more liveStream resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, cdn, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of YouTube stream IDs that identify the streams being retrieved. In a liveStream resource, the id property specifies the stream's ID.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "mine",
                            "desc": "The mine parameter can be used to instruct the API to only return streams owned by the authenticated user. Set the parameter value to true to only retrieve your own streams.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a video stream. If the properties that you want to change cannot be updated, then you need to create a new stream with the proper settings.",
                    "path": "liveStreams",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part properties that you can include in the parameter value are id, snippet, cdn, and status.\n\nNote that this method will override the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. If the request bod[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a video stream.",
                    "path": "liveStreams",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube live stream ID for the resource that is being deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a video stream. The stream enables you to send your video to YouTube, which can then broadcast the video to your audience.",
                    "path": "liveStreams",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part properties that you can include in the parameter value are id, snippet, cdn, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "i18nLanguages",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of application languages that the YouTube website supports.",
                    "path": "i18nLanguages",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the i18nLanguage resource properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hl",
                            "desc": "The hl parameter specifies the language that should be used for text values in the API response.",
                            "type": "string",
                            "default": "en_US"
                        }
                    ]
                }
            ]
        },
        {
            "name": "videoCategories",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of categories that can be associated with YouTube videos.",
                    "path": "videoCategories",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the videoCategory resource properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "regionCode",
                            "desc": "The regionCode parameter instructs the API to return the list of video categories available in the specified country. The parameter value is an ISO 3166-1 alpha-2 country code.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter specifies the language that should be used for text values in the API response.",
                            "type": "string",
                            "default": "en_US"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of video category IDs for the resources that you are retrieving.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "videos",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of videos that match the API request parameters.",
                    "path": "videos",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more video resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a video resource, the snippet property contains the channelId, title, description, tags, and categoryId properties. As such, if you set part=snippet, the API response will contain all of th[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.\n\nNote: This parameter is supported for use in conjunction with the myRating and chart parameters, but it is not supported for use in conjunction with the id parameter.",
                            "type": "uint32",
                            "default": "5",
                            "min": "1",
                            "max": "50"
                        },
                        {
                            "name": "maxWidth",
                            "desc": "The maxWidth parameter specifies a maximum width of the embedded player. If maxHeight is provided, maxWidth may not be reached in order to not violate the height request.",
                            "type": "uint32",
                            "min": "72",
                            "max": "8192"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.\n\nNote: This parameter is supported for use in conjunction with the myRating and chart parameters, but it is not supported for use in conjunction with the id parameter.",
                            "type": "string"
                        },
                        {
                            "name": "regionCode",
                            "desc": "The regionCode parameter instructs the API to select a video chart available in the specified region. This parameter can only be used in conjunction with the chart parameter. The parameter value is an ISO 3166-1 alpha-2 country code.",
                            "type": "string"
                        },
                        {
                            "name": "chart",
                            "desc": "The chart parameter identifies the chart that you want to retrieve.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "mostPopular",
                                    "desc": "Return the most popular videos for the specified content region and video category."
                                }
                            ]
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube video ID(s) for the resource(s) that are being retrieved. In a video resource, the id property specifies the video's ID.",
                            "type": "string"
                        },
                        {
                            "name": "locale",
                            "desc": "DEPRECATED",
                            "type": "string"
                        },
                        {
                            "name": "videoCategoryId",
                            "desc": "The videoCategoryId parameter identifies the video category for which the chart should be retrieved. This parameter can only be used in conjunction with the chart parameter. By default, charts are not restricted to a particular category.",
                            "type": "string",
                            "default": "0"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter instructs the API to retrieve localized resource metadata for a specific application language that the YouTube website supports. The parameter value must be a language code included in the list returned by the i18nLanguages.list method.\n\nIf localized resource details are available in that language, the resource's snippet.localized object will contain the localized values. However, if localized details are not available, the snippet.localize[...]",
                            "type": "string"
                        },
                        {
                            "name": "maxHeight",
                            "desc": "The maxHeight parameter specifies a maximum height of the embedded player. If maxWidth is provided, maxHeight may not be reached in order to not violate the width request.",
                            "type": "uint32",
                            "min": "72",
                            "max": "8192"
                        },
                        {
                            "name": "myRating",
                            "desc": "Set this parameter's value to like or dislike to instruct the API to only return videos liked or disliked by the authenticated user.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "dislike",
                                    "desc": "Returns only videos disliked by the authenticated user."
                                },
                                {
                                    "name": "like",
                                    "desc": "Returns only video liked by the authenticated user."
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "rate",
                    "desc": "Add a like or dislike rating to a video or remove a rating from a video.",
                    "path": "videos/rate",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube video ID of the video that is being rated or having its rating removed.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rating",
                            "desc": "Specifies the rating to record.",
                            "required": true,
                            "type": "string",
                            "enum": [
                                {
                                    "name": "dislike",
                                    "desc": "Records that the authenticated user disliked the video."
                                },
                                {
                                    "name": "like",
                                    "desc": "Records that the authenticated user liked the video."
                                },
                                {
                                    "name": "none",
                                    "desc": "Removes any rating that the authenticated user had previously set for the video."
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "reportAbuse",
                    "desc": "Report abuse for a video.",
                    "path": "videos/reportAbuse",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a video's metadata.",
                    "path": "videos",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nNote that this method will override the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. For example, a video's privacy setting is contained in the status part. As such, if your request is updating a private [...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a YouTube video.",
                    "path": "videos",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube video ID for the resource that is being deleted. In a video resource, the id property specifies the video's ID.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "getRating",
                    "desc": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
                    "path": "videos/getRating",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube video ID(s) for the resource(s) for which you are retrieving rating data. In a video resource, the id property specifies the video's ID.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Uploads a video to YouTube and optionally sets the video's metadata.",
                    "path": "videos",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nNote that not all parts contain properties that can be set when inserting or updating a video. For example, the statistics object encapsulates statistics that YouTube calculates for a video and does not contain values that you can set or modify. If the parameter value specifie[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "stabilize",
                            "desc": "The stabilize parameter indicates whether YouTube should adjust the video to remove shaky camera motions.",
                            "type": "bool"
                        },
                        {
                            "name": "autoLevels",
                            "desc": "The autoLevels parameter indicates whether YouTube should automatically enhance the video's lighting and color.",
                            "type": "bool"
                        },
                        {
                            "name": "notifySubscribers",
                            "desc": "The notifySubscribers parameter indicates whether YouTube should send a notification about the new video to users who subscribe to the video's channel. A parameter value of True indicates that subscribers will be notified of newly uploaded videos. However, a channel owner who is uploading many videos might prefer to set the value to False to avoid sending a notification about each new video to the channel's subscribers.",
                            "type": "bool",
                            "default": "true"
                        }
                    ]
                }
            ]
        },
        {
            "name": "watermarks",
            "methods": [
                {
                    "name": "set",
                    "desc": "Uploads a watermark image to YouTube and sets it for a channel.",
                    "path": "watermarks/set",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.upload",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter specifies the YouTube channel ID for which the watermark is being provided.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "unset",
                    "desc": "Deletes a channel's watermark image.",
                    "path": "watermarks/unset",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "channelId",
                            "desc": "The channelId parameter specifies the YouTube channel ID for which the watermark is being unset.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "captions",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of caption tracks that are associated with a specified video. Note that the API response does not contain the actual captions and that the captions.download method provides the ability to retrieve a caption track.",
                    "path": "captions",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more caption resource parts that the API response will include. The part names that you can include in the parameter value are id and snippet.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "videoId",
                            "desc": "The videoId parameter specifies the YouTube video ID of the video for which the API should return caption tracks.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of IDs that identify the caption resources that should be retrieved. Each ID must identify a caption track associated with the specified video.",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOf",
                            "desc": "ID of the Google+ Page for the channel that the request is on behalf of.",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Updates a caption track. When updating a caption track, you can change the track's draft status, upload a new caption file for the track, or both.",
                    "path": "captions",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include. Set the property value to snippet if you are updating the track's draft status. Otherwise, set the property value to id.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "sync",
                            "desc": "Note: The API server only processes the parameter value if the request contains an updated caption file.\n\nThe sync parameter indicates whether YouTube should automatically synchronize the caption file with the audio track of the video. If you set the value to true, YouTube will automatically synchronize the caption track with the audio track.",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOf",
                            "desc": "ID of the Google+ Page for the channel that the request is be on behalf of",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a specified caption track.",
                    "path": "captions",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter identifies the caption track that is being deleted. The value is a caption track ID as identified by the id property in a caption resource.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOf",
                            "desc": "ID of the Google+ Page for the channel that the request is be on behalf of",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "download",
                    "desc": "Downloads a caption track. The caption track is returned in its original format unless the request specifies a value for the tfmt parameter and in its original language unless the request specifies a value for the tlang parameter.",
                    "path": "captions/{id}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "pathParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter identifies the caption track that is being retrieved. The value is a caption track ID as identified by the id property in a caption resource.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "tfmt",
                            "desc": "The tfmt parameter specifies that the caption track should be returned in a specific format. If the parameter is not included in the request, the track is returned in its original format.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "sbv",
                                    "desc": "SubViewer subtitle."
                                },
                                {
                                    "name": "scc",
                                    "desc": "Scenarist Closed Caption format."
                                },
                                {
                                    "name": "srt",
                                    "desc": "SubRip subtitle."
                                },
                                {
                                    "name": "ttml",
                                    "desc": "Timed Text Markup Language caption."
                                },
                                {
                                    "name": "vtt",
                                    "desc": "Web Video Text Tracks caption."
                                }
                            ]
                        },
                        {
                            "name": "tlang",
                            "desc": "The tlang parameter specifies that the API response should return a translation of the specified caption track. The parameter value is an ISO 639-1 two-letter language code that identifies the desired caption language. The translation is generated by using machine translation, such as Google Translate.",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOf",
                            "desc": "ID of the Google+ Page for the channel that the request is be on behalf of",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Uploads a caption track.",
                    "path": "captions",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the caption resource parts that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "sync",
                            "desc": "The sync parameter indicates whether YouTube should automatically synchronize the caption file with the audio track of the video. If you set the value to true, YouTube will disregard any time codes that are in the uploaded caption file and generate new time codes for the captions.\n\nYou should set the sync parameter to true if you are uploading a transcript, which has no time codes, or if you suspect the time codes in your file are incorrect and want YouTube[...]",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOf",
                            "desc": "ID of the Google+ Page for the channel that the request is be on behalf of",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "i18nRegions",
            "methods": [
                {
                    "name": "list",
                    "desc": "Returns a list of content regions that the YouTube website supports.",
                    "path": "i18nRegions",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the i18nRegion resource properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hl",
                            "desc": "The hl parameter specifies the language that should be used for text values in the API response.",
                            "type": "string",
                            "default": "en_US"
                        }
                    ]
                }
            ]
        },
        {
            "name": "superChatEvents",
            "methods": [
                {
                    "name": "list",
                    "desc": "Lists Super Chat events for a channel.",
                    "path": "superChatEvents",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the superChatEvent resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "hl",
                            "desc": "The hl parameter instructs the API to retrieve localized resource metadata for a specific application language that the YouTube website supports. The parameter value must be a language code included in the list returned by the i18nLanguages.list method.\n\nIf localized resource details are available in that language, the resource's snippet.localized object will contain the localized values. However, if localized details are not available, the snippet.localize[...]",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "liveBroadcasts",
            "methods": [
                {
                    "name": "update",
                    "desc": "Updates a broadcast. For example, you could modify the broadcast settings defined in the liveBroadcast resource's contentDetails object.",
                    "path": "liveBroadcasts",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part properties that you can include in the parameter value are id, snippet, contentDetails, and status.\n\nNote that this method will override the existing values for all of the mutable properties that are contained in any parts that the parameter value specifies. For exa[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "bind",
                    "desc": "Binds a YouTube broadcast to a stream or removes an existing binding between a broadcast and a stream. A broadcast can only be bound to one video stream, though a video stream may be bound to more than one broadcast.",
                    "path": "liveBroadcasts/bind",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the unique ID of the broadcast that is being bound to a video stream.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more liveBroadcast resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, contentDetails, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "streamId",
                            "desc": "The streamId parameter specifies the unique ID of the video stream that is being bound to a broadcast. If this parameter is omitted, the API will remove any existing binding between the broadcast and a video stream.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "control",
                    "desc": "Controls the settings for a slate that can be displayed in the broadcast stream.",
                    "path": "liveBroadcasts/control",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube live broadcast ID that uniquely identifies the broadcast in which the slate is being updated.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more liveBroadcast resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, contentDetails, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "offsetTimeMs",
                            "desc": "The offsetTimeMs parameter specifies a positive time offset when the specified slate change will occur. The value is measured in milliseconds from the beginning of the broadcast's monitor stream, which is the time that the testing phase for the broadcast began. Even though it is specified in milliseconds, the value is actually an approximation, and YouTube completes the requested action as closely as possible to that time.\n\nIf you do not specify a value for[...]",
                            "type": "uint64"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "walltime",
                            "desc": "The walltime parameter specifies the wall clock time at which the specified slate change will occur. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sssZ) format.",
                            "type": "datetime"
                        },
                        {
                            "name": "displaySlate",
                            "desc": "The displaySlate parameter specifies whether the slate is being enabled or disabled.",
                            "type": "bool"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a broadcast.",
                    "path": "liveBroadcasts",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube live broadcast ID for the resource that is being deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a broadcast.",
                    "path": "liveBroadcasts",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nThe part properties that you can include in the parameter value are id, snippet, contentDetails, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a list of YouTube broadcasts that match the API request parameters.",
                    "path": "liveBroadcasts",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more liveBroadcast resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, contentDetails, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "broadcastStatus",
                            "desc": "The broadcastStatus parameter filters the API response to only include broadcasts with the specified status.",
                            "type": "string",
                            "enum": [
                                {
                                    "name": "active",
                                    "desc": "Return current live broadcasts."
                                },
                                {
                                    "name": "all",
                                    "desc": "Return all broadcasts."
                                },
                                {
                                    "name": "completed",
                                    "desc": "Return broadcasts that have already ended."
                                },
                                {
                                    "name": "upcoming",
                                    "desc": "Return broadcasts that have not yet started."
                                }
                            ]
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of YouTube broadcast IDs that identify the broadcasts being retrieved. In a liveBroadcast resource, the id property specifies the broadcast's ID.",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        },
                        {
                            "name": "broadcastType",
                            "desc": "The broadcastType parameter filters the API response to only include broadcasts with the specified type. This is only compatible with the mine filter for now.",
                            "type": "string",
                            "default": "BROADCAST_TYPE_FILTER_EVENT",
                            "enum": [
                                {
                                    "name": "all",
                                    "desc": "Return all broadcasts."
                                },
                                {
                                    "name": "event",
                                    "desc": "Return only scheduled event broadcasts."
                                },
                                {
                                    "name": "persistent",
                                    "desc": "Return only persistent broadcasts."
                                }
                            ]
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "mine",
                            "desc": "The mine parameter can be used to instruct the API to only return broadcasts owned by the authenticated user. Set the parameter value to true to only retrieve your own broadcasts.",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "transition",
                    "desc": "Changes the status of a YouTube live broadcast and initiates any processes associated with the new status. For example, when you transition a broadcast's status to testing, YouTube starts to transmit video to that broadcast's monitor stream. Before calling this method, you should confirm that the value of the status.streamStatus property for the stream bound to your broadcast is active.",
                    "path": "liveBroadcasts/transition",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "broadcastStatus",
                            "desc": "The broadcastStatus parameter identifies the state to which the broadcast is changing. Note that to transition a broadcast to either the testing or live state, the status.streamStatus must be active for the stream that the broadcast is bound to.",
                            "required": true,
                            "type": "string",
                            "enum": [
                                {
                                    "name": "complete",
                                    "desc": "The broadcast is over. YouTube stops transmitting video."
                                },
                                {
                                    "name": "live",
                                    "desc": "The broadcast is visible to its audience. YouTube transmits video to the broadcast's monitor stream and its broadcast stream."
                                },
                                {
                                    "name": "testing",
                                    "desc": "Start testing the broadcast. YouTube transmits video to the broadcast's monitor stream. Note that you can only transition a broadcast to the testing state if its contentDetails.monitorStream.enableMonitorStream property is set to true."
                                }
                            ]
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the unique ID of the broadcast that is transitioning to another status.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more liveBroadcast resource properties that the API response will include. The part names that you can include in the parameter value are id, snippet, contentDetails, and status.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "liveChatMessages",
            "methods": [
                {
                    "name": "insert",
                    "desc": "Adds a message to a live chat.",
                    "path": "liveChat/messages",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes. It identifies the properties that the write operation will set as well as the properties that the API response will include. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists live chat messages for a specific chat.",
                    "path": "liveChat/messages",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "liveChatId",
                            "desc": "The liveChatId parameter specifies the ID of the chat whose messages will be returned.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the liveChatComment resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "profileImageSize",
                            "desc": "The profileImageSize parameter specifies the size of the user profile pictures that should be returned in the result set. Default: 88.",
                            "type": "uint32",
                            "min": "16",
                            "max": "720"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter instructs the API to retrieve localized resource metadata for a specific application language that the YouTube website supports. The parameter value must be a language code included in the list returned by the i18nLanguages.list method.\n\nIf localized resource details are available in that language, the resource's snippet.localized object will contain the localized values. However, if localized details are not available, the snippet.localize[...]",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of messages that should be returned in the result set.",
                            "type": "uint32",
                            "default": "500",
                            "min": "200",
                            "max": "2000"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken property identify other pages that could be retrieved.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "delete",
                    "desc": "Deletes a chat message.",
                    "path": "liveChat/messages",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube chat message ID of the resource that is being deleted.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "liveChatModerators",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Removes a chat moderator.",
                    "path": "liveChat/moderators",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter identifies the chat moderator to remove. The value uniquely identifies both the moderator and the chat.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Adds a new moderator for the chat.",
                    "path": "liveChat/moderators",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response returns. Set the parameter value to snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists moderators for a live chat.",
                    "path": "liveChat/moderators",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "liveChatId",
                            "desc": "The liveChatId parameter specifies the YouTube live chat for which the API should return moderators.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "part",
                            "desc": "The part parameter specifies the liveChatModerator resource parts that the API response will include. Supported values are id and snippet.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "playlists",
            "methods": [
                {
                    "name": "delete",
                    "desc": "Deletes a playlist.",
                    "path": "playlists",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "id",
                            "desc": "The id parameter specifies the YouTube playlist ID for the playlist that is being deleted. In a playlist resource, the id property specifies the playlist's ID.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Creates a playlist.",
                    "path": "playlists",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Returns a collection of playlists that match the API request parameters. For example, you can retrieve all playlists that the authenticated user owns, or you can retrieve one or more playlists by their unique IDs.",
                    "path": "playlists",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter specifies a comma-separated list of one or more playlist resource properties that the API response will include.\n\nIf the parameter identifies a property that contains child properties, the child properties will be included in the response. For example, in a playlist resource, the snippet property contains properties like author, title, description, tags, and timeCreated. As such, if you set part=snippet, the API response will contain all [...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "channelId",
                            "desc": "This value indicates that the API should only return the specified channel's playlists.",
                            "type": "string"
                        },
                        {
                            "name": "hl",
                            "desc": "The hl parameter should be used for filter out the properties that are not in the given language. Used for the snippet part.",
                            "type": "string"
                        },
                        {
                            "name": "id",
                            "desc": "The id parameter specifies a comma-separated list of the YouTube playlist ID(s) for the resource(s) that are being retrieved. In a playlist resource, the id property specifies the playlist's YouTube playlist ID.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "The maxResults parameter specifies the maximum number of items that should be returned in the result set.",
                            "type": "uint32",
                            "default": "5",
                            "min": "0",
                            "max": "50"
                        },
                        {
                            "name": "onBehalfOfContentOwnerChannel",
                            "desc": "This parameter can only be used in a properly authorized request. Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwnerChannel parameter specifies the YouTube channel ID of the channel to which a video is being added. This parameter is required when a request specifies a value for the onBehalfOfContentOwner parameter, and it can only be used in conjunction with that parameter. In addition, the request must be[...]",
                            "type": "string"
                        },
                        {
                            "name": "mine",
                            "desc": "Set this parameter's value to true to instruct the API to only return playlists owned by the authenticated user.",
                            "type": "bool"
                        },
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        },
                        {
                            "name": "pageToken",
                            "desc": "The pageToken parameter identifies a specific page in the result set that should be returned. In an API response, the nextPageToken and prevPageToken properties identify other pages that could be retrieved.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "update",
                    "desc": "Modifies a playlist. For example, you could change a playlist's title, description, or privacy status.",
                    "path": "playlists",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtubepartner"
                    ],
                    "requiredQueryParams": [
                        {
                            "name": "part",
                            "desc": "The part parameter serves two purposes in this operation. It identifies the properties that the write operation will set as well as the properties that the API response will include.\n\nNote that this method will override the existing values for mutable properties that are contained in any parts that the request body specifies. For example, a playlist's description is contained in the snippet part, which must be included in the request body. If the request do[...]",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "onBehalfOfContentOwner",
                            "desc": "Note: This parameter is intended exclusively for YouTube content partners.\n\nThe onBehalfOfContentOwner parameter indicates that the request's authorization credentials identify a YouTube CMS user who is acting on behalf of the content owner specified in the parameter value. This parameter is intended for YouTube content partners that own and manage many different YouTube channels. It allows content owners to authenticate once and get access to all their vid[...]",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "channelBanners",
            "methods": [
                {
                    "name": "insert",
[...]
