{
    "kind": "discovery#restDescription",
    "etag": "",
    "discoveryVersion": "v1",
    "id": "people:v1",
    "name": "people",
    "version": "v1",
    "title": "Google People API",
    "description": "Provides access to information about profiles and contacts.",
    "documentationLink": "https://developers.google.com/people/",
    "protocol": "rest",
    "rootUrl": "https://people.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/plus.login"
        ]
    },
    "resources": [
        {
            "name": "people",
            "methods": [
                {
                    "name": "getBatchGet",
                    "desc": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.",
                    "path": "v1/people:batchGet",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "requestMask.includeField",
                            "desc": "Comma-separated list of fields to be included in the response. Omitting\nthis field will include all fields except for connections.list requests,\nwhich have a default mask that includes common fields like metadata, name,\nphoto, and profile url.\nEach path should start with `person.`: for example, `person.names` or\n`person.photos`.",
                            "type": "string"
                        },
                        {
                            "name": "resourceNames",
                            "desc": "The resource name, such as one returned by\n[`people.connections.list`](/people/api/rest/v1/people.connections/list),\nof one of the people to provide information about. You can include this\nparameter up to 50 times in one request.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Provides information about a person resource for a resource name. Use\n`people/me` to indicate the authenticated user.",
                    "path": "v1/{+resourceName}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/contacts",
                        "https://www.googleapis.com/auth/contacts.readonly",
                        "https://www.googleapis.com/auth/plus.login",
                        "https://www.googleapis.com/auth/user.addresses.read",
                        "https://www.googleapis.com/auth/user.birthday.read",
                        "https://www.googleapis.com/auth/user.emails.read",
                        "https://www.googleapis.com/auth/user.phonenumbers.read",
                        "https://www.googleapis.com/auth/userinfo.email",
                        "https://www.googleapis.com/auth/userinfo.profile"
                    ],
                    "pathParams": [
                        {
                            "name": "resourceName",
                            "desc": "The resource name of the person to provide information about.\n\n- To get information about the authenticated user, specify `people/me`.\n- To get information about any user, specify the resource name that\n  identifies the user, such as the resource names returned by\n  [`people.connections.list`](/people/api/rest/v1/people.connections/list).",
                            "required": true,
                            "type": "string",
                            "pattern": "^people/[^/]+$"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "requestMask.includeField",
                            "desc": "Comma-separated list of fields to be included in the response. Omitting\nthis field will include all fields except for connections.list requests,\nwhich have a default mask that includes common fields like metadata, name,\nphoto, and profile url.\nEach path should start with `person.`: for example, `person.names` or\n`person.photos`.",
                            "type": "string"
                        }
                    ]
                }
            ],
            "resources": [
                {
                    "name": "connections",
                    "methods": [
                        {
                            "name": "list",
                            "desc": "Provides a list of the authenticated user's contacts merged with any\nlinked profiles.",
                            "path": "v1/{+resourceName}/connections",
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/contacts",
                                "https://www.googleapis.com/auth/contacts.readonly"
                            ],
                            "pathParams": [
                                {
                                    "name": "resourceName",
                                    "desc": "The resource name to return connections for. Only `people/me` is valid.",
                                    "required": true,
                                    "type": "string",
                                    "pattern": "^people/[^/]+$"
                                }
                            ],
                            "optinalQueryParams": [
                                {
                                    "name": "sortOrder",
                                    "desc": "The order in which the connections should be sorted. Defaults to\n`LAST_MODIFIED_ASCENDING`.",
                                    "type": "string",
                                    "enum": [
                                        {
                                            "name": "LAST_MODIFIED_ASCENDING"
                                        },
                                        {
                                            "name": "FIRST_NAME_ASCENDING"
                                        },
                                        {
                                            "name": "LAST_NAME_ASCENDING"
                                        }
                                    ]
                                },
                                {
                                    "name": "requestSyncToken",
                                    "desc": "Whether the response should include a sync token, which can be used to get\nall changes since the last request.",
                                    "type": "bool"
                                },
                                {
                                    "name": "pageToken",
                                    "desc": "The token of the page to be returned.",
                                    "type": "string"
                                },
                                {
                                    "name": "pageSize",
                                    "desc": "The number of connections to include in the response. Valid values are\nbetween 1 and 500, inclusive. Defaults to 100.",
                                    "type": "int32"
                                },
                                {
                                    "name": "requestMask.includeField",
                                    "desc": "Comma-separated list of fields to be included in the response. Omitting\nthis field will include all fields except for connections.list requests,\nwhich have a default mask that includes common fields like metadata, name,\nphoto, and profile url.\nEach path should start with `person.`: for example, `person.names` or\n`person.photos`.",
                                    "type": "string"
                                },
                                {
                                    "name": "syncToken",
                                    "desc": "A sync token, returned by a previous call to `people.connections.list`.\nOnly resources changed since the sync token was created will be returned.",
                                    "type": "string"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}