{
    "kind": "discovery#restDescription",
    "etag": "\"tbys6C40o18GZwyMen5GMkdK-3s/ijeguRXyVpN9uEUSOI4kjLGOD9E\"",
    "discoveryVersion": "v1",
    "id": "fitness:v1",
    "name": "fitness",
    "version": "v1",
    "title": "Fitness",
    "description": "Stores and accesses user data in the fitness store from apps on any platform.",
    "documentationLink": "https://developers.google.com/fit/rest/",
    "protocol": "rest",
    "rootUrl": "https://www.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/fitness.blood_glucose.write",
            "https://www.googleapis.com/auth/fitness.blood_pressure.write",
            "https://www.googleapis.com/auth/fitness.location.write",
            "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
            "https://www.googleapis.com/auth/fitness.activity.write",
            "https://www.googleapis.com/auth/fitness.blood_glucose.read",
            "https://www.googleapis.com/auth/fitness.body.write",
            "https://www.googleapis.com/auth/fitness.location.read",
            "https://www.googleapis.com/auth/fitness.reproductive_health.read",
            "https://www.googleapis.com/auth/fitness.reproductive_health.write",
            "https://www.googleapis.com/auth/fitness.activity.read",
            "https://www.googleapis.com/auth/fitness.nutrition.read",
            "https://www.googleapis.com/auth/fitness.nutrition.write",
            "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
            "https://www.googleapis.com/auth/fitness.body_temperature.write",
            "https://www.googleapis.com/auth/fitness.body.read",
            "https://www.googleapis.com/auth/fitness.body_temperature.read",
            "https://www.googleapis.com/auth/fitness.blood_pressure.read"
        ]
    },
    "resources": [
        {
            "name": "users",
            "resources": [
                {
                    "name": "sessions",
                    "methods": [
                        {
                            "name": "delete",
                            "desc": "Deletes a session specified by the given session ID.",
                            "path": "{userId}/sessions/{sessionId}",
                            "httpMethod": "DELETE",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Delete a session for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "sessionId",
                                    "desc": "The ID of the session to be deleted.",
                                    "required": true,
                                    "type": "string"
                                }
                            ],
                            "optinalQueryParams": [
                                {
                                    "name": "currentTimeMillis",
                                    "desc": "The client's current time in milliseconds since epoch.",
                                    "type": "int64"
                                }
                            ]
                        },
                        {
                            "name": "list",
                            "desc": "Lists sessions previously created.",
                            "path": "{userId}/sessions",
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "List sessions for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                }
                            ],
                            "optinalQueryParams": [
                                {
                                    "name": "includeDeleted",
                                    "desc": "If true, deleted sessions will be returned. When set to true, sessions returned in this response will only have an ID and will not have any other fields.",
                                    "type": "bool"
                                },
                                {
                                    "name": "pageToken",
                                    "desc": "The continuation token, which is used to page through large result sets. To get the next page of results, set this parameter to the value of nextPageToken from the previous response.",
                                    "type": "string"
                                },
                                {
                                    "name": "startTime",
                                    "desc": "An RFC3339 timestamp. Only sessions ending between the start and end times will be included in the response.",
                                    "type": "string"
                                },
                                {
                                    "name": "endTime",
                                    "desc": "An RFC3339 timestamp. Only sessions ending between the start and end times will be included in the response.",
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "update",
                            "desc": "Updates or insert a given session.",
                            "path": "{userId}/sessions/{sessionId}",
                            "httpMethod": "PUT",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Create sessions for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "sessionId",
                                    "desc": "The ID of the session to be created.",
                                    "required": true,
                                    "type": "string"
                                }
                            ],
                            "optinalQueryParams": [
                                {
                                    "name": "currentTimeMillis",
                                    "desc": "The client's current time in milliseconds since epoch.",
                                    "type": "int64"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "dataSources",
                    "methods": [
                        {
                            "name": "get",
                            "desc": "Returns the specified data source.",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Retrieve a data source for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "dataSourceId",
                                    "desc": "The data stream ID of the data source to retrieve.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "list",
                            "desc": "Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to other developers, or calls using other scopes.",
                            "path": "{userId}/dataSources",
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "List data sources for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                }
                            ],
                            "optinalQueryParams": [
                                {
                                    "name": "dataTypeName",
                                    "desc": "The names of data types to include in the list. If not specified, all data sources will be returned.",
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "patch",
                            "desc": "Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.\n\nData sources are identified by their dataStreamId. This method supports patch semantics.",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "PATCH",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Update the data source for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "dataSourceId",
                                    "desc": "The data stream ID of the data source to update.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "update",
                            "desc": "Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.\n\nData sources are identified by their dataStreamId.",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "PUT",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Update the data source for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "dataSourceId",
                                    "desc": "The data stream ID of the data source to update.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "create",
                            "desc": "Creates a new data source that is unique across all data sources belonging to this user. The data stream ID field can be omitted and will be generated by the server with the correct format. The data stream ID is an ordered combination of some fields from the data source. In addition to the data source fields reflected into the data source ID, the developer project number that is authenticated when creating the data source is included. This developer project n[...]",
                            "path": "{userId}/dataSources",
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Create the data source for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        },
                        {
                            "name": "delete",
                            "desc": "Deletes the specified data source. The request will fail if the data source contains any data points.",
                            "path": "{userId}/dataSources/{dataSourceId}",
                            "httpMethod": "DELETE",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Retrieve a data source for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                },
                                {
                                    "name": "dataSourceId",
                                    "desc": "The data stream ID of the data source to delete.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        }
                    ],
                    "resources": [
                        {
                            "name": "datasets",
                            "methods": [
                                {
                                    "name": "delete",
                                    "desc": "Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "DELETE",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ],
                                    "pathParams": [
                                        {
                                            "name": "userId",
                                            "desc": "Delete a dataset for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "dataSourceId",
                                            "desc": "The data stream ID of the data source that created the dataset.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "datasetId",
                                            "desc": "Dataset identifier that is a composite of the minimum data point start time and maximum data point end time represented as nanoseconds from the epoch. The ID is formatted like: \"startTime-endTime\" where startTime and endTime are 64 bit integers.",
                                            "required": true,
                                            "type": "string"
                                        }
                                    ],
                                    "optinalQueryParams": [
                                        {
                                            "name": "currentTimeMillis",
                                            "desc": "The client's current time in milliseconds since epoch.",
                                            "type": "int64"
                                        },
                                        {
                                            "name": "modifiedTimeMillis",
                                            "desc": "When the operation was performed on the client.",
                                            "type": "int64"
                                        }
                                    ]
                                },
                                {
                                    "name": "get",
                                    "desc": "Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "GET",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.read",
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.read",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.read",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.read",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ],
                                    "pathParams": [
                                        {
                                            "name": "userId",
                                            "desc": "Retrieve a dataset for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "dataSourceId",
                                            "desc": "The data stream ID of the data source that created the dataset.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "datasetId",
                                            "desc": "Dataset identifier that is a composite of the minimum data point start time and maximum data point end time represented as nanoseconds from the epoch. The ID is formatted like: \"startTime-endTime\" where startTime and endTime are 64 bit integers.",
                                            "required": true,
                                            "type": "string"
                                        }
                                    ],
                                    "optinalQueryParams": [
                                        {
                                            "name": "limit",
                                            "desc": "If specified, no more than this many data points will be included in the dataset. If there are more data points in the dataset, nextPageToken will be set in the dataset response.",
                                            "type": "int32"
                                        },
                                        {
                                            "name": "pageToken",
                                            "desc": "The continuation token, which is used to page through large datasets. To get the next page of a dataset, set this parameter to the value of nextPageToken from the previous response. Each subsequent call will yield a partial dataset with data point end timestamps that are strictly smaller than those in the previous partial response.",
                                            "type": "string"
                                        }
                                    ]
                                },
                                {
                                    "name": "patch",
                                    "desc": "Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics.",
                                    "path": "{userId}/dataSources/{dataSourceId}/datasets/{datasetId}",
                                    "httpMethod": "PATCH",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/fitness.activity.write",
                                        "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                        "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                        "https://www.googleapis.com/auth/fitness.body.write",
                                        "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                        "https://www.googleapis.com/auth/fitness.location.write",
                                        "https://www.googleapis.com/auth/fitness.nutrition.write",
                                        "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                        "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                                    ],
                                    "pathParams": [
                                        {
                                            "name": "userId",
                                            "desc": "Patch a dataset for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "dataSourceId",
                                            "desc": "The data stream ID of the data source that created the dataset.",
                                            "required": true,
                                            "type": "string"
                                        },
                                        {
                                            "name": "datasetId",
                                            "desc": "Dataset identifier that is a composite of the minimum data point start time and maximum data point end time represented as nanoseconds from the epoch. The ID is formatted like: \"startTime-endTime\" where startTime and endTime are 64 bit integers.",
                                            "required": true,
                                            "type": "string"
                                        }
                                    ],
                                    "optinalQueryParams": [
                                        {
                                            "name": "currentTimeMillis",
                                            "desc": "The client's current time in milliseconds since epoch. Note that the minStartTimeNs and maxEndTimeNs properties in the request body are in nanoseconds instead of milliseconds.",
                                            "type": "int64"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "dataset",
                    "methods": [
                        {
                            "name": "aggregate",
                            "desc": "Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggreated into exactly one bucket type per request.",
                            "path": "{userId}/dataset:aggregate",
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/fitness.activity.read",
                                "https://www.googleapis.com/auth/fitness.activity.write",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.read",
                                "https://www.googleapis.com/auth/fitness.blood_glucose.write",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.read",
                                "https://www.googleapis.com/auth/fitness.blood_pressure.write",
                                "https://www.googleapis.com/auth/fitness.body.read",
                                "https://www.googleapis.com/auth/fitness.body.write",
                                "https://www.googleapis.com/auth/fitness.body_temperature.read",
                                "https://www.googleapis.com/auth/fitness.body_temperature.write",
                                "https://www.googleapis.com/auth/fitness.location.read",
                                "https://www.googleapis.com/auth/fitness.location.write",
                                "https://www.googleapis.com/auth/fitness.nutrition.read",
                                "https://www.googleapis.com/auth/fitness.nutrition.write",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.read",
                                "https://www.googleapis.com/auth/fitness.oxygen_saturation.write",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.read",
                                "https://www.googleapis.com/auth/fitness.reproductive_health.write"
                            ],
                            "pathParams": [
                                {
                                    "name": "userId",
                                    "desc": "Aggregate data for the person identified. Use me to indicate the authenticated user. Only me is supported at this time.",
                                    "required": true,
                                    "type": "string"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}