{
    "kind": "discovery#restDescription",
    "etag": "\"tbys6C40o18GZwyMen5GMkdK-3s/UEKDxDt-gBRW5wBq_kkcVGVpuQc\"",
    "discoveryVersion": "v1",
    "id": "replicapoolupdater:v1beta1",
    "name": "replicapoolupdater",
    "version": "v1beta1",
    "title": "Google Compute Engine Instance Group Updater API",
    "description": "[Deprecated. Please use compute.instanceGroupManagers.update method. replicapoolupdater API will be disabled after December 30th, 2016] Updates groups of Compute Engine instances.",
    "documentationLink": "https://cloud.google.com/compute/docs/instance-groups/manager/#applying_rolling_updates_using_the_updater_service",
    "labels": [
        "limited_availability"
    ],
    "protocol": "rest",
    "rootUrl": "https://www.googleapis.com/",
    "auth": {
        "oauth2": [
            "https://www.googleapis.com/auth/replicapool.readonly",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only",
            "https://www.googleapis.com/auth/replicapool"
        ]
    },
    "resources": [
        {
            "name": "rollingUpdates",
            "methods": [
                {
                    "name": "listInstanceUpdates",
                    "desc": "Lists the current status for each instance within a given update.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "filter",
                            "desc": "Optional. Filter expression for filtering listed resources.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Optional. Maximum count of results to be returned. Maximum value is 500 and default value is 500.",
                            "type": "uint32",
                            "default": "500",
                            "min": "0",
                            "max": "500"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Optional. Tag returned by a previous list request truncated by maxResults. Used to continue a previous list request.",
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "pause",
                    "desc": "Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "resume",
                    "desc": "Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "rollback",
                    "desc": "Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "cancel",
                    "desc": "Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "get",
                    "desc": "Returns information about an update.",
                    "path": "{project}/zones/{zone}/rollingUpdates/{rollingUpdate}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "rollingUpdate",
                            "desc": "The name of the update.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "insert",
                    "desc": "Inserts and starts a new update.",
                    "path": "{project}/zones/{zone}/rollingUpdates",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.",
                    "path": "{project}/zones/{zone}/rollingUpdates",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/replicapool",
                        "https://www.googleapis.com/auth/replicapool.readonly"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "The Google Developers Console project name.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "The name of the zone in which the update's target resides.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "filter",
                            "desc": "Optional. Filter expression for filtering listed resources.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Optional. Maximum count of results to be returned. Maximum value is 500 and default value is 500.",
                            "type": "uint32",
                            "default": "500",
                            "min": "0",
                            "max": "500"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Optional. Tag returned by a previous list request truncated by maxResults. Used to continue a previous list request.",
                            "type": "string"
                        }
                    ]
                }
            ]
        },
        {
            "name": "zoneOperations",
            "methods": [
                {
                    "name": "get",
                    "desc": "Retrieves the specified zone-specific operation resource.",
                    "path": "{project}/zones/{zone}/operations/{operation}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "Name of the project scoping this request.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "Name of the zone scoping this request.",
                            "required": true,
                            "type": "string"
                        },
                        {
                            "name": "operation",
                            "desc": "Name of the operation resource to return.",
                            "required": true,
                            "type": "string"
                        }
                    ]
                },
                {
                    "name": "list",
                    "desc": "Retrieves the list of Operation resources contained within the specified zone.",
                    "path": "{project}/zones/{zone}/operations",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/replicapool"
                    ],
                    "pathParams": [
                        {
                            "name": "project",
                            "desc": "Name of the project scoping this request.",
                            "required": true,
                            "type": "string",
                            "pattern": "(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))"
                        },
                        {
                            "name": "zone",
                            "desc": "Name of the zone scoping this request.",
                            "required": true,
                            "type": "string"
                        }
                    ],
                    "optinalQueryParams": [
                        {
                            "name": "filter",
                            "desc": "Optional. Filter expression for filtering listed resources.",
                            "type": "string"
                        },
                        {
                            "name": "maxResults",
                            "desc": "Optional. Maximum count of results to be returned. Maximum value is 500 and default value is 500.",
                            "type": "uint32",
                            "default": "500",
                            "min": "0",
                            "max": "500"
                        },
                        {
                            "name": "pageToken",
                            "desc": "Optional. Tag returned by a previous list request truncated by maxResults. Used to continue a previous list request.",
                            "type": "string"
                        }
                    ]
                }
            ]
        }
    ]
}